### PR TITLE
chore(deps): Bump httpclient from 4.5.10 to 4.5.13

### LINKED ISSUE #725: Upgrade HttpClient to 4.5.13 or later
### Description

Simply, please merge #713!

### Info

n/a

### PR DESCRIPTION
**Pull request by tadayosi**
## Description
Fix #725. Thanks!

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by tadayosi** [comment]
Hi @rohanKanojia could you have a look?  The last failing codecov check doesn't seem to be relevant to this fix.

**Comment by rohanKanojia** [comment]
You're right. it seems to be complaining about coverage which I don't think we should worry about in a version bump PR

**Review by rohanKanojia — APPROVED** [review]

**Comment by tadayosi** [comment]
@manusa @rohanKanojia Is there any reason why it's not accepted yet?  Thank you.

**Comment by manusa** [comment]
> @manusa @rohanKanojia Is there any reason why it's not accepted yet? Thank you.

We need the Eclipse legal team to approve a CQ for the updated dependency.

Everything looks good, so as soon as it gets approved we'll merge. Should be part of the next release.

**Comment by rohanKanojia** [comment]
CQs required for this PR:
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23527
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23528

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
