### PR TITLE
Fix: Refactor tests in `KeyStoreUtilTest` to avoid duplication (#472)

### PR DESCRIPTION
**Pull request by deepak-gittyup**
## Description
Fixes: #472 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] ~~I Added [CHANGELOG](../CHANGELOG.md) entry~~
 - [ ] I have implemented unit tests to cover my changes
 - [ ] ~~I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly~~
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] ~~I tested my code in Kubernetes~~
 - [ ] ~~I tested my code in OpenShift~~

### CODE REVIEW

**Comment by dengliming** [comment]
I suggest using `junit parameterized tests `

**Comment by deepak-gittyup** [comment]
> I suggest using `junit parameterized tests `

Hi @dengliming 
From what I can see in the code, all the tests don't seem to have the same body
* There are 5 tests and 3 of those (`loadPrivateKeyPKCS8`, `loadPrivateKeyECDSA`, `loadPrivateKeyDefault`) fall in one category having same body with the only difference being the private key file. For this case, it makes sense to use parameterized tests
* But the next 2 tests (`loadInvalidPrivateKey` and `createKeyStore`), although they need an input private key path/cert path, I see that they have a different body and perform slightly different assertions from the other 3

From what I understood, to support parameterized tests, I need to separate the 5 tests into 2 separate classes: 3 + 2
Have I misunderstood anything here ?

**Comment by deepak-gittyup** [comment]
Hi @rohanKanojia 
In the previous few PR attempts, there were 2 check failures and the reasons were:
* My git config was pointing to a different user.email other than the one that I had used to register in the eclipse community 
* I had passed incorrect key to one of the tests which had caused the coverage to drop by 0.01%
All other checks had passed
After correcting both of them, I was expecting all checks to pass. Yet 2 of them failed and from what I can see, they don't seem to be related to any of my change (Apologies if I am wrong here)

Is this a one time unexpected failure ? 
If so how do I rerun the checks again ? 
Should I do a dummy commit to trigger it ?

**Comment by rohanKanojia** [comment]
Yes, it seems unrelated to your changes. I've restarted the workflow :+1:

**Comment by deepak-gittyup** [comment]
> Yes, it seems unrelated to your changes. I've restarted the workflow 👍

Thanks @rohanKanojia 
One check still seems to have failed
From what I understand, looks like the shutdown hook in `PortForwardService` seems to have not been called while running `PortForwardServiceTest`
Perhaps some kind of unexpected/abrupt termination ?

Is it okay to go ahead despite this ?

**Comment by rohanKanojia** [comment]
Yes, I think it's fine. Need to check with @manusa if we should split tests into two classes for parametrized approach  as suggested by @dengliming   or is it fine this way

**Comment by manusa** [comment]
Hi,

Issue #472 was probably unnecessary since these tests were already quite readable and semantic.

However, since the issue is here, the only valid approach is via parameterized tests.
The current solution makes the tests more opaque since the test logic is hidden in a method with no semantic meaning `loadAndTestPrivateKey` (It tells what it does, but neither how nor what it asserts).

So if you want to keep at it, create the parameterized tests (find an example [here](https://github.com/manusa/jkube/blob/e03e87cca97bf703f9a8a6e2605b00dafb48b87d/jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/MicronautUtilsGetMicronautConfigurationTest.java#L31))

Yes, for clarity you should split tests. Each parameterized suite should go on its own class. The name of the class should be declarative enough to suggest what we are testing.

**Comment by rohanKanojia** [comment]
@deepak-gittyup: Hi, polite ping. Are you still working on this patch?

**Comment by alex81sp** [comment]
I can pick it up

**Comment by alex81sp** [comment]
This PR could be closed,
completed here https://github.com/eclipse/jkube/pull/531

**Comment by rohanKanojia** [comment]
Closing this since the issue is fixed by #531

**Pull request closed without merging**
