### PR TITLE
Updated Quarkus quickstart version to latest Quarkus version #1430

### LINKED ISSUE #1430: [Maven Quickstarts] : Update Maven Quarkus quickstart to latest Quarkus version 2.7.5.Final
### Description
Our current Quarkus maven quickstart seems to be outdated. It needs to be updated to latest version of Quarkus.

https://github.com/eclipse/jkube/blob/ded7049e0ff253e04ebf1fddfc265bf25f1b636b/quickstarts/maven/quarkus/pom.xml#L35

- [ ] Update Quarkus version to latest release
- [ ] Verify Kubernetes Maven Plugin is working with the updated version by deploying an application to [minikube](https://minikube.sigs.k8s.io/docs/)
- [ ] Verify OpenShift Maven Plugin is working with updated version by deploying the application to [Red Hat Developer Sandbox](https://developers.redhat.com/developer-sandbox/get-started)

### PR DESCRIPTION
**Pull request by anurag-rajawat**
## Description

Fixes #1430 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Have you verified whether project is deployed okay under all profiles when deployed with jkube ?

**Comment by anurag-rajawat** [comment]
Yes, it is deployed okay under all profiles.

**Comment by manusa** [comment]
Changes:
- Use the now latest version 2.8.1.Final (L44)
- Remove the profile `dev` (L103-L108), it's no longer needed with `quarkus:dev`

Please, also make sure to verify the native packaging and deployment (`-Pnative-docker`)

**Review by manusa — CHANGES_REQUESTED** [review]
https://github.com/eclipse/jkube/pull/1435#issuecomment-1111750775

**Comment by anurag-rajawat** [comment]
@manusa I've verified native packaging and deployment and it is deployed successfully under all profiles.

**Review by manusa — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
I see a new minor version [2.9.0.Final](https://github.com/quarkusio/quarkus/releases/tag/2.9.0.Final) got released yesterday. Shall we bump version to 2.9.0.Final?

**Comment by manusa** [comment]
> I see a new minor version [2.9.0.Final](https://github.com/quarkusio/quarkus/releases/tag/2.9.0.Final) got released yesterday. Shall we bump version to 2.9.0.Final?

Let's merge this first.

**Pull request merged**
