### PR TITLE
Changing the Scope of fields in the ArchiveService to final issue #1781.

### PR DESCRIPTION
**Pull request by ishu-thakur**
Changing the Scope of fields in the ArchiveService to final issue #1781.

### CODE REVIEW

**Comment by manusa** [comment]
Hi @ishu-thakur 
You've already contributed to the project, issues labeled with `first-timers-only` are limited to first time contributors to the project (and at most one).
The whole point of these very simple issues is for people to get acquainted with the project, with the Eclipse Foundation processes, and in general with free open source software. Consider that it takes longer for me to create the issue than to create the actual fix. We believe that these kind of issues help the community and this is why we put an extra-effort submitting them, if a single contributor was to tackle all of these issues, our effort would be wasted.

**Comment by ishu-thakur** [comment]
Hi @manusa yes sure i understand that :) so if there is any issue that is not first time only but beginner as i am new to contribution i would like to contribute , and sorry i just didnt know about it thats why i raised the PR by fixing the issues but i will keep this time in my mind and thanks for guiding me :).

**Comment by manusa** [comment]
No worries, we usually tag these issues with [`help wanted`](https://github.com/eclipse/jkube/labels/help%20wanted). There are not many right now our time for these tasks is absorbed by GSoC and Hacktoberfest.

**Pull request closed without merging**
