### PR TITLE
refactor(jkube-kit/config): Refactoring DockerFileBuilder collections to be final

### LINKED ISSUE #1807: [Hacktoberfest] DockerFileBuilder fields may be 'final'
### Description
The following statements are reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/85008d4274a9aa6f0d0a047370d8dcb8c696d7ac/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilder.java#L72-L87
 
- [ ] should be changed to:
```java
    private final List<CopyEntry> copyEntries = new ArrayList<>();

    // list of ports to expose and environments to use
    private final List<String> ports = new ArrayList<>();

    // list of RUN Commands to run along with image build see issue #191 on github
    private final List<String> runCmds = new ArrayList<>();

    // environment
    private final Map<String,String> envEntries = new LinkedHashMap<>();

    // image labels
    private final Map<String, String> labels = new LinkedHashMap<>();

    // exposed volumes
    private final List<String> volumes = new ArrayList<>();
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by singloon**
Signed-off-by: Ka Lan Leung <kalanleung@outlook.com>

## Description

Fixes #1807

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by singloon** [comment]
[K8S v1.24.0 quarkus (#1827)](https://github.com/jkubeio/ci/actions/runs/3229104345/jobs/5286049187) seems to be timing out trying to get dependency from repo1.maven.org

`Failed to execute goal on project quarkus-rest: Could not resolve dependencies for project org.eclipse.jkube.integration-tests:quarkus-rest:jar:0.0.0-SNAPSHOT: Could not transfer artifact io.quarkus:quarkus-ide-launcher:jar:2.8.3.Final from/to central (https://repo1.maven.org/maven2): transfer failed for https://repo1.maven.org/maven2/io/quarkus/quarkus-ide-launcher/2.8.3.Final/quarkus-ide-launcher-2.8.3.Final.jar: Connect to repo1.maven.org:443 [repo1.maven.org/146.75.28.209] failed: Connection timed out (Connection timed out) -> [Help 1]
 `

**Comment by rohanKanojia** [comment]
@singloon : ECA check is failing. Have you created Eclipse account and signed Eclipse Contributor Agreement?

**Comment by singloon** [comment]
@rohanKanojia 
image

**Comment by rohanKanojia** [comment]
@singloon : Are you sure you used same email as the one linked in commit/PR description?

**Comment by singloon** [comment]
@rohanKanojia is was passing yesterday before the checks were run again
image

**Comment by singloon** [comment]
@rohanKanojia fixed

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
