### PR TITLE
Fix #1374

### LINKED ISSUE #1374: HealthCheckConfigTest : Use assertThrows instead of `@Test(expected = IllegalArgumentException.class)` annotation
### Description
Right now we're using this `expected` annotation for verifying exception thrown in test. We should use `Assert.assertThrows` instead since it's move flexible and level returns thrown exception's object which can be asserted further if necessary

https://github.com/eclipse/jkube/blob/b45facd5b3dd25a31850d2f38b96c73edf66b83a/jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/HealthCheckConfigTest.java#L95-L154

- [x] Remove `expected` annotation from test and use `assertThrows`
- [ ] Try to check if these can be converted into a parameterized test

### PR DESCRIPTION
**Pull request by Devamparikh**
## Description
Fix https://github.com/eclipse/jkube/issues/1374: Replaced the expected annotation with Assert.assertThrows in HealthCheckConfigTest.java for exceptions verification with improvments.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have implemented unit tests to cover my changes
 - [x] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

Do let me know if something goes wrong.

### CODE REVIEW

**Comment by Devamparikh** [comment]
Isn't this PR ready to merge?

**Comment by rohanKanojia** [comment]
> Isn't this PR ready to merge?

It needs to be reviewed first.

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
What's up with #1398, both seem to be implementing the same changes? If this one is an update of the other, maybe you should close that.

**Review by manusa — APPROVED** [review]

**Pull request merged**
