### PR TITLE
Used diamond operator in new HashMap() constructors and replaced Coll…

### LINKED ISSUE #1536: UserConfigurationCompareTest : Use diamond operator `<>` for generics
### Description
UserConfigurationCompareTest seems to have some places where we're doing raw declaration (i.e. collection type without any information of the element type). 

https://github.com/eclipse/jkube/blob/8df189ce4f331b7677251f653606c9e2cc899324/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompareTest.java#L68-L69

https://github.com/eclipse/jkube/blob/8df189ce4f331b7677251f653606c9e2cc899324/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompareTest.java#L81-L82

Also, we could use type safe `Collections.emptyMap()` here:
https://github.com/eclipse/jkube/blob/8df189ce4f331b7677251f653606c9e2cc899324/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompareTest.java#L56

### AC
- [x] Use diamond operator in `new HashMap()` constructor
- [x] Replace `Collections.EMPTY_MAP` with `Collections.emptyMap()`

### PR DESCRIPTION
**Pull request by nabeelkhan10**
Fix #1536

Made the changes that were assigned to me.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@nabeelkhan10 : Thanks, changes look good. However, I'm not sure whether you created Eclipse Acocunt and signed Eclipse Contributor Agreement.

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Comment by rohanKanojia** [comment]
No need to create new PR. Just amend this commit and force push.

```
git commit --amend --signoff
git push origin master
```

**Comment by nabeelkhan10** [comment]
It says 'fatal: you have nothing to amend.'

**Comment by rohanKanojia** [comment]
strange, I don't get this error.

**Comment by nabeelkhan10** [comment]
What should I do now?

**Comment by nabeelkhan10** [comment]
I did git commit with message then it worked but now git push is now working

**Comment by anurag-rajawat** [comment]
@nabeelkhan10 you've to force push
```text
git push -f origin <branchName>
```

**Comment by nabeelkhan10** [comment]
Still I am getting the same msg

**Comment by nabeelkhan10** [comment]
@rohanKanojia what should I do?

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by nabeelkhan10** [comment]
Can you assign any beginner-friendly issues to me?

**Pull request merged**
