### PR TITLE
chore: remove child class field from UndeployMojo

### LINKED ISSUE #2640: Fix `jkube-kit/build/service` module's unit tests on Windows
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/1338

:warning: A windows machine is required to reproduce and fix problems in this issue.

_Originally posted by @l3002 in https://github.com/eclipse/jkube/issues/2629#issuecomment-1933484184_

> a few tests are still failing in `jkube-kit/build/service` module. Here's a screenshot for your reference

When running `mvn clean install` on Windows, I see the following tests failing in `jkube-kit/build/service` module:

- [WatchServiceTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java)

TODO: Figure out what's not working as expected and propose a way to fix this

Screenshot 2024-02-08 124307

### PR DESCRIPTION
**Pull request by BalaganeshA2k**
## Description

Fixes #2640 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

Acceptance Criteria
 - [x] Fields with matching name in AbstractJKubeMojo are removed from UndeployMojo

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2654 (_2024-02-11T12:35:38Z_)

:gear: [JKube E2E Tests (7861990738)](https://github.com/jkubeio/ci/actions/runs/7861990738) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2654)](https://github.com/jkubeio/ci/actions/runs/7861990738/job/21450987209)

**Comment by rohanKanojia** [comment]
@BalaganeshA2k : This issue is created for contributors who have already contributed their first PR to project. 

Could you please look into [`first-timers-only` ](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only)type issues?

**Comment by BalaganeshA2k** [comment]
Okay Rohan 👍🏻. Will do the first-timers-only.

**Comment by BalaganeshA2k** [comment]
Hello Rohan Kumar,
I've raised a PR for first-timers-only type issues
PR: https://github.com/eclipse/jkube/pull/2664

Thanks

**Pull request closed without merging**
