### PR TITLE
assertion: junit -> assertj

### PR DESCRIPTION
**Pull request by danmikes**
## Description

Assertions changed: Junit -> AssertJ

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by danmikes** [comment]
I hope this time I complied to all rules.

**Comment by manusa** [comment]
Hi,

Looking good.

Make sure you signed the ECA  with your Eclipse Account, you need to log in to Eclipse and sign it.

image

**Comment by danmikes** [comment]
I signed the ECA with Eclipse

**Comment by manusa** [comment]
I can confirm that the email address which signed-off the commit has a valid ECA agreement, I'm not sure what's wrong with the workflow.

image

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
