### PR TITLE
Fix#469: replaced Java.net.URL with Java.net.URI

### PR DESCRIPTION
**Pull request by maycap123**
## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by maycap123** [comment]
Ok it seems that i have to fix 3 new code smells, dang it. :D

**Comment by maycap123** [comment]
I don't understand the failed test from SonarCloud and from codecov. what is code coverage?

**Comment by rohanKanojia** [comment]
It's complaining that new code added is not covered via tests.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
