### PR TITLE
#1783 issue: Update AuthConfigFactory.java

### PR DESCRIPTION
**Pull request by coderdeadpool**
Fixes # (issue)

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 
 
 - [x] My code follows the style guidelines of this project
 - [x]  I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I Added [CHANGELOG](https://github.com/eclipse/jkube/CHANGELOG.md) entry
 - [x] I have updated the [documentation](https://github.com/eclipse/jkube/kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by coderdeadpool** [comment]
hello reviewers
i am new to the open source community. 
can anyone tell me that what are these above errors and why it is occuring

**Comment by rohanKanojia** [comment]
@coderdeadpool : Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Comment by coderdeadpool** [comment]
i have created an Eclipse Account and Signed the agreement @rohanKanojia what do i have to do now.
can you explain me in detail. i need your little help here

**Pull request closed without merging**
