### PR TITLE
VolumePermissionEnricher : Replace iteration with bulk Collection.addAll call

### PR DESCRIPTION
**Pull request by Prathamkrishna**
…All call #1362

## Description
 VolumePermissionEnricher : Replace iteration with bulk Collection.addAll call #1362 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by fig666** [comment]
this action can't be run administered change in plugin can't be reintegrated

**Comment by fig666** [comment]
> Kudos, SonarCloud Quality Gate passed!&nbsp; &nbsp; Quality Gate passed
> 
> [Bug](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=BUG)  
> [Vulnerability](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=VULNERABILITY)  
> [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=SECURITY_HOTSPOT)  
> [Code Smell](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=1391&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=jkubeio_jkube&pullRequest=1391&metric=new_coverage&view=list) [100.0% Coverage](https://sonarcloud.io/component_measures?id=jkubeio_jkube&pullRequest=1391&metric=new_coverage&view=list)  
> [](https://sonarcloud.io/component_measures?id=jkubeio_jkube&pullRequest=1391&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=jkubeio_jkube&pullRequest=1391&metric=new_duplicated_lines_density&view=list)
> 
> 

command rejected and not confirmed . this can't be overidden

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM thx!

**Pull request merged**
