### PR TITLE
Fix #854: %n should be used in place of \n to produce the platform-specific line separator. 

### LINKED ISSUE #854: `%n` should be used in place of `\n` to produce the platform-specific line separator.
We have this use of `\n` in `String.format` statements here which is a line delimiter on Linux:

https://github.com/eclipse/jkube/blob/5a1828c0ece30567fdcf89ce7668bb8c2003211d/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java#L269-L273

We should use `%n` instead which will be portable across different platforms.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by Onyinye91-ctrl**
Fix #854 
 - [x] Bug fix (non-breaking change which fixes an issue) #854

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Comment by Onyinye91-ctrl** [comment]
@rohanKanojia I have created the account and submitted the agreement. But i am getting an error while running the code on git. This is the error message 
"fatal: not in a git directory"

**Comment by rohanKanojia** [comment]
Are you sure you're in correct git repository? looks like you're running git commands in some other folder. Please feel free to reach out to us on chat for help if you're stuck https://gitter.im/eclipse/jkube

**Comment by Onyinye91-ctrl** [comment]
@rohanKanojia here is the screenshot
git

**Comment by rohanKanojia** [comment]
@Onyinye91-ctrl : Hi, I think your commit was updated locally but maybe you forgot to push it to your github.
```
git push origin master -f
```

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
