### PR TITLE
Fix #471: Remove the declaration of thrown runtime exceptions across javadoc

### LINKED ISSUE #471: Remove the declaration of thrown runtime exceptions across codebase.
### Description

There are a few places in our codebase where we have `throws XYZException` in our methods, even if `XYZException` is a `RuntimeException`. We should refactor these places to remove these throw occurrences. Consider this place:
https://github.com/eclipse/jkube/blob/90439cb98fef038e8c991825d2a90ce414787fb6/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerHostConfig.java#L95-L98

This should actually look like this:
```java
public ContainerHostConfig extraHosts(List<String> extraHosts) { 
     // ...
}
```

You can find out these places via a simple grep command:
```bash
jkube : $ git grep -in "throws KubernetesClientException\|throws IllegalArgumentException\|throws NumberFormatException\|throws ExternalConfigHandlerException"
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerCreateConfig.java:75:    public ContainerCreateConfig environment(String envPropsFile, Map<String, String> env, Map mavenProps) throws IllegalArgumentException {
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerHostConfig.java:95:    public ContainerHostConfig extraHosts(List<String> extraHosts) throws IllegalArgumentException {
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/PortMapping.java:85:     * @throws IllegalArgumentException if the format doesn't fit
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/PortMapping.java:261:    private String createPortSpec(String port, String protocol) throws NumberFormatException {
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/PortMapping.java:341:    private void parsePortMapping(String input) throws IllegalArgumentException {
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/ExternalConfigHandler.java:45:     * @throws ExternalConfigHandlerException if there is a problem resolving the image configuration
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/ExternalConfigHandler.java:48:        throws ExternalConfigHandlerException;
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/ImageConfigResolver.java:69:     * @throws IllegalArgumentException if no type is given when an external reference configuration is provided
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/compose/ComposeUtils.java:68:     * @throws IllegalArgumentException if {@code pathToResolve} is relative, and {@code project} is {@code null} or
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/PropertyMode.java:36:     * @throws IllegalArgumentException if empty or invalid names
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/DockerPathUtil.java:43:     * @throws IllegalArgumentException if the supplied {@code baseDir} does not represent an absolute path
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/VolumeBindingUtil.java:158:     * @throws IllegalArgumentException if the supplied {@code baseDir} is not absolute
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/VolumeBindingUtil.java:220:     * @throws IllegalArgumentException if the supplied {@code baseDir} is not absolute
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java:117:     * @throws IllegalArgumentException exception if arguement is invalid
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java:119:    public static String validateKubernetesId(String currentValue, String description) throws IllegalArgumentException {
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java:232:     * d@throws IllegalArgumentException if the name doesnt validate
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilder.java:109:     * @throws IllegalArgumentException if no src/dest entries have been added
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ProcessorConfig.java:120:     * @throws IllegalArgumentException if the includes reference an non existing element
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java:1225:    public void doCreateJob(Job job, String namespace, String sourceName) throws KubernetesClientException {

```

For more information, you can check this sonar rule[0]

[0] https://sonarcloud.io/organizations/jkubeio/rules?open=java%3AS1130&rule_key=java%3AS1130

### PR DESCRIPTION
**Pull request by theexplorist**
Fix  #471 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@theexplorist: Thanks a lot for PR :+1: . There is just a minor conflict and I think it's good to be merged once resolved.

**Comment by theexplorist** [comment]
@manusa @rohanKanojia  Conflict resolved!

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
