### PR TITLE
chore: maven-surefire-plugin 3.0.0-M5

### PR DESCRIPTION
**Pull request by sullis**
## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
- [ ] CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22643

**Comment by sullis** [comment]
WDYT?  @rohanKanojia

**Comment by rohanKanojia** [comment]
@sullis : In my opinion, it's fine to have this change in. This PR is pending review from @manusa

**Comment by rohanKanojia** [comment]
@sullis: Could you please rebase and push again? CircleCI check seems stuck somehow :confused:

**Review by manusa — APPROVED** [review]

**Comment by rohanKanojia** [comment]
strange, CircleCI workflows don't seem to be running :confused:

**Pull request merged**
