### PR TITLE
added re-interrupt mechanism for issue 966

### LINKED ISSUE #966: PortForwardTask.java: Either re-interrupt this method or rethrow the "InterruptedException" that can be caught here.
### Description
The following statement is reported as a Bug by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXhZi-zIMtwvSXpgYorv&open=AXhZi-zIMtwvSXpgYorv):
 
https://github.com/eclipse/jkube/blob/af40c8f27af57f9651f8ebb1634df33eaf909f6a/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/portforward/PortForwardTask.java#L49-L51
 
- [x] should be changed to:
```java
    } catch (InterruptedException ex) {
      Thread.currentThread().interrupt();
    } catch (Exception exception) {
      logger.warn("Not able to port forward: %s", exception.getMessage());
    } finally {
```

#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by Attyuttam**
## Description
Fix #966
Signed-off-by: attyuttam <attyuttam@gmail.com>

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Comment by Attyuttam** [comment]
Hi, @sunix / @manusa . Can you please have a look into this PR and approve if everything looks good. Much appreciated. Thank you. 

I am not sure how the merge is carried out, is it one of the reviewers who merges the PRs or the person who created the PR ?

**Comment by rohanKanojia** [comment]
We require at least 2 approvals to merge PRs. Once we get 2 approvals, we can proceed to merge.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
