### PR TITLE
Fixing code style issue with declaration

### LINKED ISSUE #1799: [Hacktoberfest] DefaultLogCallback fields may be 'final'
### Description
The following statement is reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/c15c4bb8b7cc4ea7502f8314b1e067b27f9a1dda/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/DefaultLogCallback.java#L32
 
- [x] should be changed to:
```java
    private static final Map<String, SharedPrintStream> printStreamMap = new HashMap<>();
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by jivjen**
## Description

Fixes #1799 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by anurag-rajawat** [comment]
Hi! @jivjen 
Thanks a lot for contributing to Eclipse JKube 👍

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a Signed-off-by: footer. You can do it like this:

Amend your previous commit with signed off footer
```shell
git commit --amend --signoff
```

**Comment by jivjen** [comment]
> Hi! @jivjen Thanks a lot for contributing to Eclipse JKube 👍
> 
> In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a Signed-off-by: footer. You can do it like this:
> 
> Amend your previous commit with signed off footer
> 
> ```shell
> git commit --amend --signoff
> ```

@anurag-rajawat I created an account with the same email id and signed the ECA but still the check is failing for some reason. Any idea what might the issue be?
image

**Comment by anurag-rajawat** [comment]
> @anurag-rajawat I created an account with the same email id and signed the ECA but still the check is failing for some reason. Any idea what might the issue be?

Maybe because of not re-validating your PR after signing the ECA.
Please revalidate.

**Pull request merged**
