### PR TITLE
GitHub Actions checkout v2

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@sullis : Hi, Thanks for your contribution. In order to contribute to Eclipse related projects you need to sign [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php). Could you please sign this so that we can proceed and merge this?

**Comment by rohanKanojia** [comment]
@manusa : could you please review this one ?

**Comment by manusa** [comment]
Change is OK, but commit needs to be signed off by an e-mail with a valid [Eclipse account](https://accounts.eclipse.org/) that has agreed to the "[Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)"

e.g.:
image

**Comment by rohanKanojia** [comment]
@sullis : Could you please sign the agreement whenever you get time?

**Comment by rohanKanojia** [comment]
Closing due to inactivity, I've opened #76 and ported your changes.

**Pull request closed without merging**
