### PR TITLE
Add support for Quarkus Fast Jar Packaging

### PR DESCRIPTION
**Pull request by dloiacono**
Signed-off-by: dloiacono <dloiacono@gmail.com>

## Description
Quarkus 1.12 was released last month which made Fast-jar packaging as default. Earlier we used to run *-runner.jar in previous versions, but now it's replaced by this:

java -jar target/quarkus-app/quarkus-run.jar
You can read more about it here.

Right now users can't use jkube in zero-configuration mode with Fast Jar. JKube fails with not being able to find -runner.jar:

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.1.1:build (default-cli) on project rosa-fruits-app: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.1.1:build failed: Can't find single file with suffix '-runner.jar' in /home/rohaan/work/repos/rosa-fruits-app/target (zero or more than one files found ending with '-runner.jar') ->
We would need to make changes to QuarkusGenerator to handle Fast-jar packaging as well. We just need to build ImageConfiguration like done in this Dockerfile here

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [X] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
Intends to fix #632 
This is not really the expected approach because you can configure Quarkus to produce an uber-jar or not depending on your config (see `quarkus.package.type` property).

So  the assumption that depending on a given Quarkus version you will get one packaging or the other is not completely right.

We should basically try to detect the main JAR package with some other means. Also, taking into account other configurations such as `quarkus.package.runner-suffix` that might affect the generated JAR.

Since al of this is hard, what might work in most cases is detecting the target/*.jar that matches the application name as prefix. Also adding an enricher configuration in case this could be overridden manually.

**Comment by dloiacono** [comment]
Sounds reasonable to me.
And what about the "quarkus-app" folder in the target?

**Comment by manusa** [comment]
I'm not sure, I haven't had the chance to analyze the non uber-jar mode.

It seems that when running in fast-jar mode, `quarkus-app` is always generated (https://quarkus.io/guides/maven-tooling#using-fast-jar), right?

If the above is true, and stable across different versions (<1.12 too), we should try to infer the packaging mode by the structure of the target/build directory:
- Is native: proceed with native assembly
- Is fast-jar (---> `quarkus-app` exists): Generated assembly should copy files in `target/quarkus-app/*` to `/deployments`
- fast-jar not detected (---> `target/lib` subdirectory exists + fat jar in `target`): Generate assembly as we are doing now
- Other: Copy fattest jar in `/target` to `/deployments` (same as JavaExec)

Something along those lines should work.

**Comment by dloiacono** [comment]
Seems that only when the `quarkus-app` forder is present in the target the logic have to be changed.

**Comment by dloiacono** [comment]
@rohanKanojia I forgot to add also the Openshift version of the Helm Push mojo.
Is the case to add it?

**Comment by rohanKanojia** [comment]
@dloiacono : I think it makes sense to add it, @manusa  WDYT?. You can add OpenShiftHelmPushMojo which will just extend original one just like most of it's goals

**Review by manusa — APPROVED** [review]

**Pull request merged**
