### PR TITLE
Remove deprecated ExpectedException and Rule annotation, use assertThrows instead in test classes

### PR DESCRIPTION
**Pull request by dolatapatryk**
## Description

This PR resolves the following issue: #1040.

If you have any suggestions please go ahead, I'll be happy to fix that.

If you liked my work, I'd be glad if you could mark this PR as hacktoberfest-accepted. Thanks!

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Maybe ECA check validates all commits for Signed-Off footer. Could you please squash all commits into a single commit(`git rebase -i`)?

**Comment by dolatapatryk** [comment]
@rohanKanojia Ok, I would try in a minute. But do you think that if I've got Eclipse account with username `pdolata` and signed of commit with my gh username `dolatapatryk` is that a problem? Emails are the same.

**Comment by dolatapatryk** [comment]
@rohanKanojia I squashed commits and there is still an error. Eca check shows something like that: "Failures for: patrykdolata@****.local" but I don't know where this address comes from :/

**Comment by dolatapatryk** [comment]
@rohanKanojia It's interesting fact that if you check this branch's report directly on codecov it says that coverage is `48.91%` not like in gh pipeline.

**Pull request merged**
