### PR TITLE
Removed unused imports

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
I'm sorry there is similar PR with same change #820

**Comment by mohitsaxenaknoldus** [comment]
> I'm sorry there is similar PR with same change #820

Oh...didn't notice. Should i close this one then?

**Comment by rohanKanojia** [comment]
@mohitsaxenaknoldus : Sorry for the confusion. Umm, since you already created the PR. I think we can keep it but target a different file. 

I see some unused imports in these files:

https://github.com/eclipse/jkube/blob/master/jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherManager.java#L22

https://github.com/eclipse/jkube/blob/master/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ServiceConfig.java#L23

Could you please update your PR to remove unused imports in these files instead?

**Comment by rohanKanojia** [comment]
I see ECA check is failing.

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Comment by mohitsaxenaknoldus** [comment]
> @mohitsaxenaknoldus : Sorry for the confusion. Umm, since you already created the PR. I think we can keep it but target a different file.
> 
> I see some unused imports in these files:
> 
> https://github.com/eclipse/jkube/blob/master/jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherManager.java#L22
> 
> https://github.com/eclipse/jkube/blob/master/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ServiceConfig.java#L23
> 
> Could you please update your PR to remove unused imports in these files instead?

Sure! Thanks! I am on it.

**Comment by manusa** [comment]
Hi @mohitsaxenaknoldus 
ECA is still missing:
image

**Comment by mohitsaxenaknoldus** [comment]
@rohanKanojia I am waiting on account activation from the Eclipse side since yesterday and it is not letting me sign the ECA without login, Any other way I can sign that?

**Comment by rohanKanojia** [comment]
In order to sign ECA, Eclipse Account is required. Usually account creation is quick.

According to [Eclipse status](https://www.eclipsestatus.io), website seems down. Maybe you can try it again after some time.

**Comment by mohitsaxenaknoldus** [comment]
> In order to sign ECA, Eclipse Account is required. Usually account creation is quick.
> 
> According to [Eclipse status](https://www.eclipsestatus.io), website seems down. Maybe you can try it again after some time.

I contacted them through the mail and they told me that Eclipse Foundation is on a holiday from July 30th to August 9th. Guess we have to wait till 9 before my account gets activated:

> Thank you for reaching out.
>
> Membership Coordination will be out of the office from July 31, 2021
> until Monday August 9, 2021.

**Comment by rohanKanojia** [comment]
@mohitsaxenaknoldus: Hi, Could you please try again? Maybe the Eclipse infra team resolved the outage.

**Comment by mohitsaxenaknoldus** [comment]
> @mohitsaxenaknoldus: Hi, Could you please try again? Maybe the Eclipse infra team resolved the outage.

Yes, they were back in the office today and they have activated my account. I've also signed the agreement. I'll push the final code tomorrow so we can finally close this. Thanks a lot for your support!

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
