### PR TITLE
chore: #1070 Removing unused ClasspathIncludeProcessor asciidoctorj processor

### PR DESCRIPTION
**Pull request by sunix**
## Description
Fix https://github.com/eclipse/jkube/issues/1070 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by sunix** [comment]
> use the asciidoctorj version that is coming as a transitive dependency of the maven-asciidoctor-plugin, do not override it.

Note that I finally kept the declaration of `asciidoctorj` as the version should be aligned with `asciidoctorj-diagram` version

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
There's still this checkbox for #1070:
```
use the asciidoctorj version that is coming as a transitive dependency of the maven-asciidoctor-plugin, do not override it.
```

Can we remove that dependency now (dependencyManagement, pluginManagement, etc.)?

**Comment by sunix** [comment]
@manusa 
https://github.com/eclipse/jkube/pull/1119#issuecomment-969210620
I think we want to keep managing the version of asciidoctorj as we are including asciidoctorj-diagram and these 2 have to be aligned

**Pull request merged**
