### PR TITLE
Update Kubernetes Client from 5.0.0 to 5.1.1 #592

### PR DESCRIPTION
**Pull request by apupier**
and align (transitive) dependencies

## Description

upgrading to latest Kubernetes Client 5.1.1 #592

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

First draft. Currently failing:

```
com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
 in 'reader', line 6, column 5:
        app: test
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 9, column 34:
        helm-variable: "(( required "A valid .Values.global_template_ ... 
                                     ^

 at [Source: (StringReader); line: 9, column: 34]
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:359)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:868)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:894)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:652)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:869)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:652)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:540)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:377)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at org.eclipse.jkube.kit.resource.helm.HelmServiceIT.assertYamls(HelmServiceIT.java:87)
	at org.eclipse.jkube.kit.resource.helm.HelmServiceIT.generateHelmChartsTest(HelmServiceIT.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: while parsing a block mapping
 in 'reader', line 6, column 5:
        app: test
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 9, column 34:
        helm-variable: "(( required "A valid .Values.global_template_ ... 
                                     ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:355)
	... 39 more
```

### CODE REVIEW

**Comment by apupier** [comment]
when using Java 11, there is also this error:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jkube-kit-common: Compilation failure
Error:  /home/runner/work/jkube/jkube/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Base64Util.java:[18,22] package javax.xml.bind does not exist
```
https://github.com/eclipse/jkube/pull/593/checks?check_run_id=2005263011#step:5:391

but do not see why this PR woudl introduce that.

**Comment by rohanKanojia** [comment]
looks like this kubernetes client upgrade is somehow breaking out Helm support-related tests(both `HelmServiceIT` and `helm-and-fragments` IT are breaking).

**Comment by manusa** [comment]
Hi, I'll try to check this out later today.
We also need to create the appropriate CQs for this PR to be merged (Fabric8 + Jackson)

**Comment by manusa** [comment]
## Contribution Questionnaires (CQs)

- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23092

**Comment by apupier** [comment]
Helm tests fixed.

Now, next issue reported by tests is that it doesn't work with OpenShift 3.9:

https://github.com/eclipse/jkube/pull/593/checks?check_run_id=2015432291#step:6:48

```
Starting OpenShift using openshift/origin:v3.9.0 ...
FAIL
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Error: could not start OpenShift container "origin"
   Details:
     Last 10 lines of "origin" container log:
     github.com/openshift/origin/pkg/cmd/server/start.NewCommandStartAllInOne.func1(0xc420048240, 0xc421202900, 0x0, 0x2)
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_allinone.go:89 +0x125
     github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420048240, 0xc421202780, 0x2, 0x2, 0xc420048240, 0xc421202780)
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x234
     github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420435d40, 0xc420078008, 0xc420435d40, 0x2)
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
     github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420435d40, 0x9, 0xc420435d40)
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
     main.main()
     	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.9.0/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:36 +0x24b

Error: Command failed: oc cluster up --routing-suffix="127.0.0.1.${OC_DOMAIN:-nip.io}" 
Error: Command failed: oc cluster up --routing-suffix="127.0.0.1.${OC_DOMAIN:-nip.io}"
```
**

**Comment by rohanKanojia** [comment]
This should get fixed as soon as we merge https://github.com/eclipse/jkube/pull/598

**Comment by manusa** [comment]
Even if tests pass, take into account we won't be able to merge until [the CQs](https://github.com/eclipse/jkube/pull/593#issuecomment-789064179) get approved by the Eclipse Legal team.

**Comment by apupier** [comment]
it remains a single CQ to be validated: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23096

**Comment by apupier** [comment]
> it remains a single CQ to be validated: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23096

validated too.
All CQs are validated

**Comment by manusa** [comment]
@apupier My changes to tests were lost after your last push, did you change anything else? can I force push my local branch?

**Comment by manusa** [comment]
> @apupier My changes to tests were lost after your last push, did you change anything else? can I force push my local branch?

OK, I rebased my branch and saw it was only about the Changelog. I'm force-pushing my rebased branch.

**Review by manusa — APPROVED** [review]
LGTM, thx

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
Merged, thx a lot! :heart:

**Comment by apupier** [comment]
> @apupier My changes to tests were lost after your last push, did you change anything else? can I force push my local branch?

oh, I'm very sorry, I forgot to that you pushed a new version. That's really my fault. I had just resolved the conflict with the changelog.
I see that you redid things correctly. thank you very much.

**Pull request merged**
