### PR TITLE
ImageName should throw exception when digest length is too small

### LINKED ISSUE #2543: ImageName should throw exception when digest length is too small
### Component

None

### Description

ImageName seems to do a very simple validation on Digest in image name:
https://github.com/eclipse/jkube/blob/b47fa4a9ab9a839bd4f8a093b4b0a4d8e9c88e9f/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java#L353

This allows even image names with invalid digest like `repo@sha256:ffffffffffffffffffffffffffffffffff` to pass validation check.

We need to update the Digest regexp to match what's used in [Docker Distribution](https://github.com/distribution/reference/blob/8507c7fcf0da9f570540c958ea7b972c30eeaeca/regexp.go#L81C15-L81C86):
```
[A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*[:][[:xdigit:]]{32,}
```

### Expected Behavior
ImageName digest regexp should be more strict

### Acceptance Criteria
- [ ] ImageName's digest regexp is updated with what's in Docker Distribution

### PR DESCRIPTION
**Pull request by Devashishbasu**
fixes #2543

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2557 (_2024-01-15T12:29:36Z_)

:gear: [JKube E2E Tests (7528854819)](https://github.com/jkubeio/ci/actions/runs/7528854819) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2557)](https://github.com/jkubeio/ci/actions/runs/7528854819/job/20491912081)

**Comment by Devashishbasu** [comment]
Hii @rohanKanojia when i am updating the digest regex with mentioned in the issue [A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*[:][[:xdigit:]]{32,} some tests in ImageNameFullNameParseTest is failing but when i updated digest regex with "^(?:sha256:)?[a-fA-F0-9]{64}$" all test cases passed in ImageNameFullNameParseTest....can you please review it?

**Comment by rohanKanojia** [comment]
This issue aimed to align our regex to match what's in docker source. We need to investigate why those tests have started failing. Are those tests having valid SHA 256 digests in expectations? Or the digest regex that I mentioned in the issue is not the correct one?

**Comment by Devashishbasu** [comment]
> This issue aimed to align our regex to match what's in docker source. We need to investigate why those tests have started failing. Are those tests having valid SHA 256 digests in expectations? Or the digest regex that I mentioned in the issue is not the correct one?

Hi @rohanKanojia i have updated the digest's regex to match with whats in docker distribution .....but some test cases are failing...this invalid digest repo@sha256:ffffffffffffffffffffffffffffffffff which you mentioned in the issue was passing previously is failing now and  some more test cases are failing for example...

19@sha256:b7d8650e04b282b9d7b94daedf38321512f9910bce896cd40ffa15b1b92bab17' is invalid:
   * digest part 'sha256:b7d8650e04b282b9d7b94daedf38321512f9910bce896cd40ffa15b1b92bab17' doesn't match allowed pattern '^[A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*[:][[:xdigit:]]{32,}$'

'127.0.0.1:5000/hello-world@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9' is invalid:
   * digest part 'sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9' doesn't match allowed pattern '^[A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*[:][[:xdigit:]]{32,}$'



if the digest's regex is correct than i think these failing test cases do not have valid SHA 256 digests

**Comment by rohanKanojia** [comment]
@Devashishbasu : Do the tests pass if you replace existing digests with some valid doest?

**Pull request closed without merging**
