### PR TITLE
ResourceValidator fields Changed to 'final'

### LINKED ISSUE #1866: [Hacktoberfest] ResourceValidator fields may be 'final'
### Description
The following statements are reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/e4782b525d314ecb03d5d24932b60c3140e40aab/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/validator/ResourceValidator.java#L56-L58
 
- [x] should be changed to:
```java
    private final File[] resources;
    private ResourceClassifier target = ResourceClassifier.KUBERNETES;
    private final List<ValidationRule> ignoreValidationRules = new ArrayList<>();
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by KPriSM29**
## Description

Fixes #1866

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by KPriSM29** [comment]
> ### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)
> Started new GH workflow run for #1893 (_2022-11-07T08:48:30Z_)
> 
> gear [JKube E2E Tests (3408817901)](https://github.com/jkubeio/ci/actions/runs/3408817901)
> 
> * x [Bootstrap CI test run (#1893)](https://github.com/jkubeio/ci/actions/runs/3408817901/jobs/5669845397)
> * x [K8S ${{ matrix.kubernetes }} ${{ matrix.suite }} (#${{ github.event.client_payload.pr }})](https://github.com/jkubeio/ci/actions/runs/3408817901/jobs/5669853548)
> * x [OpenShift ${{ matrix.openshift }} ${{ matrix.suite }} (#${{ github.event.client_payload.pr }})](https://github.com/jkubeio/ci/actions/runs/3408817901/jobs/5669853423)
> * x [Windows (#${{ github.event.client_payload.pr }})](https://github.com/jkubeio/ci/actions/runs/3408817901/jobs/5669853659)
> * heavy_check_mark [Finish CI test run](https://github.com/jkubeio/ci/actions/runs/3408817901/jobs/5669853773)

Hey, I thought this was a good for beginner issue, 
I tried following the guidelines but couldn't go through 

the code is too huge to navigate,
how to proceed could you please guide me here?

**Comment by anurag-rajawat** [comment]
Hi @KPriSM29 
You can check out this [blog](https://rohaan.medium.com/how-to-contribute-to-eclipse-jkube-f3bc7f902bf4) by Rohan to understand and contribute to the project.

**Comment by anurag-rajawat** [comment]
Hi @KPriSM29 
You can check out this [blog](https://rohaan.medium.com/how-to-contribute-to-eclipse-jkube-f3bc7f902bf4) to understand and contribute to the project

**Comment by KPriSM29** [comment]
Thanks, will surely read the blog and the documentation too 👍🏻 @anurag-rajawat

**Comment by manusa** [comment]
PR open more than a month ago but ECA was never signed and issues never fixed, closing.

**Pull request closed without merging**
