### PR TITLE
refactor: Java Security Ultimate Security Repo Scanner 2023

### PR DESCRIPTION
**Pull request by caytec**
Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/TkgUEiqd7?organizationId=RWNsaXBzZSBGb3VuZGF0aW9u

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@caytec : Thanks for your PR. Is it possible to split this PR into multiple PRs focusing on a single issue at a time? It would be easier for us to review it.

**Comment by caytec** [comment]
Wery well, very well then, our minions and some other great minds collected together could detect something useful o7 I am just a freelance senior IT hacker planning on going more into forward IT Business areas as a Project Manager or CEO with a cut with my dad who is well known drone builder Szymon Kupaj owning Farada Group in central Europe Lubieszow having his own drone factory for medical facitlities etc. We are currently testing our ways of repurposing the older or more vulnerable aging coding into something which can grow old without many hiccups - let's AI help us instead of rule us until we have time left, if they remain helpful we may keep such exchange going forward as we grow the business :) 

Nah, I didn't signed any Eclipse Account, nor also I am new to the legal agremeets needed for sending you guys any 'commits' which can go forward as something useful. If you can get me more info about this process, so we can contribute more into you guys, as we are currently try to master Java software dection and you guys seem to have many to help us improve the contribution. I would commit even more if something is needed.

I never been at Hacktoberfest. Hmmm... Should I? Never met anyone much invested into tech through my life, would be great to build and grow new connections for new possibilties I think :) You guys would be an attendants here or someone in the staff kind of things?

**Comment by rohanKanojia** [comment]
@caytec : I see. Thanks for introducing yourself.

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Pull request closed without merging**
