### PR TITLE
Changing the fields of AutoPullMode .

### PR DESCRIPTION
**Pull request by ishu-thakur**
Making the fields in AutoPullMode file 'final'  for the issue #1784

### CODE REVIEW

**Comment by anurag-rajawat** [comment]
Hi @ishu-thakur!
Thanks a lot for contributing to Eclipse JKube 👍

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a Signed-off-by: footer. You can do it like this:

### Amend your previous commit with signed off footer
```shell
git commit --amend --signoff
```

**Comment by ishu-thakur** [comment]
Hi @anurag-rajawat i have create an eclipse account and Sign Eclipse Contributor Agreement and also have amend the commit by signoff :) please check .

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
