### PR TITLE
Initial support for Gitpod (#1946)

### LINKED ISSUE #1946: Add support for Gitpod
### Component

_No response_

### Is your enhancement related to a problem? Please describe

As a contributor, I want to work on projects from different environments. It would be nice to have a prebuilt dev environment such as [Gitpod](https://www.gitpod.io) to spin up the prebuilt dev environment.

This would allow contributors to contribute without worrying about their OS, project dependencies, installing tools, etc.

### Describe the solution you'd like

One solution to this is add a `.gitpod.yml` file to support [Gitpod](https://www.gitpod.io)

### Describe alternatives you've considered

_No response_

### Additional context
https://gitter.im/eclipse/jkube?at=62daeee522c53438bcc84411
https://gitter.im/eclipse/jkube?at=62de88f48fe56a38b5d8e46c

### PR DESCRIPTION
**Pull request by anurag-rajawat**
## Description

Fixes #1946 

To get a preview of this click [here](https://gitpod.io/#github.com/anurag-rajawat/jkube/tree/gitpod)

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
I think it would be nice to have some alignment with the tasks @sunix proposed in the equivalent [`devfile.yaml`](https://github.com/eclipse/jkube/blob/c52505bee50cba4b0f6c52e7bbbd001a0011d4ee/devfile.yaml)

**Comment by sunix** [comment]
For the tasks, these are the ones I am using: https://github.com/eclipse/jkube/blob/master/devfile.yaml#L100-L231

The `prebuild` concept is very interesting this is actually what I was doing "manually":  https://github.com/eclipse/jkube/blob/master/devfile.yaml#L48

**Comment by anurag-rajawat** [comment]
@manusa and @sunix as per [Gitpod docs](https://www.gitpod.io/docs/configure/workspaces/tasks) there are three types of tasks:
1. `before` to customize the terminal or install global project dependencies
2. `init` for heavy-lifting tasks such as downloading dependencies or compiling source code.
3. `command` to start your database or development server.

In our case `init` task makes more sense. So I think we can't add all the tasks defined in devfile https://github.com/eclipse/jkube/blob/master/devfile.yaml#L100-L231
But if we want to do any specific task then we can do it manually as we do in our local workstation.

**Comment by anurag-rajawat** [comment]
> I like having predefined commands that help me doing things like "build current project with all dependent modules" which turns out to be very handy when we don't want to rebuild everything, but maybe it is only my personal preferences. 

I also like it and I tried the `command` task to add the other task but it's not working. I also tried it with [wait for commands to complete](https://www.gitpod.io/docs/configure/workspaces/tasks#wait-for-commands-to-complete) still not working.
So I asked the Gitpod community how can we add predefined commands. https://discord.com/channels/816244985187008514/1052228526545313882/1052228526545313882

**Comment by anurag-rajawat** [comment]
> > I like having predefined commands that help me doing things like "build current project with all dependent modules" which turns out to be very handy when we don't want to rebuild everything, but maybe it is only my personal preferences.
> 
> I also like it and I tried the `command` task to add the other task but it's not working. I also tried it with [wait for commands to complete](https://www.gitpod.io/docs/configure/workspaces/tasks#wait-for-commands-to-complete) still not working. So I asked the Gitpod community how can we add predefined commands. https://discord.com/channels/816244985187008514/1052228526545313882/1052228526545313882

I got a reply from the gitpod community and they gave a reference to https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml and there I didn't find anything which can help us to add predefined commands.
So how do you want to proceed with this @sunix?
Feel free to close if this doesn't meet your expectations.

**Review by manusa — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Review by sunix — APPROVED** [review]

**Comment by anurag-rajawat** [comment]
@sunix yes it will be good for contributors and I've updated contribution guidelines in https://github.com/jkubeio/jkube-website/pull/69

**Comment by rohanKanojia** [comment]
@anurag-rajawat : Could you please rebase your PR against master (hopefully one last time :crossed_fingers: ) . Let's get this merged within this week.

**Pull request merged**
