### PR TITLE
Removed guava #2286

### PR DESCRIPTION
**Pull request by Devashishbasu**
Removed guava dependency
#2286

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2511 (_2024-01-03T02:28:29Z_)

:gear: [JKube E2E Tests (7392813410)](https://github.com/jkubeio/ci/actions/runs/7392813410) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2511)](https://github.com/jkubeio/ci/actions/runs/7392813410/job/20111813461)

**Comment by rohanKanojia** [comment]
I think we're dependent on guava module due to jkube-kit/build/service/jib module.

**Comment by Devashishbasu** [comment]
> I think we're dependent on guava module due to jkube-kit/build/service/jib module.

So should I try to fix the Required Statuses or move to another issue??

**Comment by manusa** [comment]
The issue is about removing the Guava dependency (and its usages). Guava is used throughout (maybe less now after a few prior refactors) the project. It's not a simple replacement and it doesn't qualify as a good first issue.
The first step to remove any Guava-related piece of code is to provide tests to verify that the functionality provided by Guava remains after its removal.

**Pull request closed without merging**
