### PR TITLE
Replace Integer type by int one in SecretEnricher class

### LINKED ISSUE #2757: SecretEnricher : Use primitive `int` instead of `Integer` in for loop
### Component

JKube Kit

### Description
I see a boxed Integer type getting used as a local for loop scope variable:

https://github.com/eclipse/jkube/blob/3afc7bf1f8dbe4452826c5ec7ec58de5c9408d53/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecretEnricher.java#L85

Generally, it's better to rely on primitives unless we need to use these types in collections.

### Expected Behavior
`Integer` is replaced with `int` 

### Acceptance Criteria
- [x] `Integer` is replaced with `int` in for loop 
- [x] SecretEnricherTest passes after making this change

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by arsenalzp**
## Description

Replace loop for with Stream API

Use primitive int instead of Integer in for loop, replace loop of Map by Collection stream.
Fixes #2757 

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] My code follows the style guidelines of this project
 - [X] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [X] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [X] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [X] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [X] New and existing unit tests pass locally with my changes
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2805 (_2024-03-12T19:02:59Z_)

:gear: [JKube E2E Tests (8254375392)](https://github.com/jkubeio/ci/actions/runs/8254375392) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2805)](https://github.com/jkubeio/ci/actions/runs/8254375392/job/22578393666)

**Comment by rohanKanojia** [comment]
@arsenalzp I remember you were also talking about adding a test for this class.

**Comment by arsenalzp** [comment]
> @arsenalzp I remember you were also talking about adding a test for this class.

Hello,
Of course, I will create another issue for test of SecretEnricher class.

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@arsenalzp : There is a minor code smell related to unused import. Could you please remove it?

**Comment by arsenalzp** [comment]
> @arsenalzp : There is a minor code smell related to unused import. Could you please remove it?

Sure!

**Comment by arsenalzp** [comment]
I guess you mixed up this PR with other one - #2807 . There were a couple of unused Mock imports.

**Comment by rohanKanojia** [comment]
@arsenalzp : I'm referring to https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=2805&resolved=false&inNewCodePeriod=true

**Comment by arsenalzp** [comment]
> @arsenalzp : I'm referring to https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=2805&resolved=false&inNewCodePeriod=true

Fixed.
Thank you!

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
