### PR TITLE
KarafGenerator misses jolokia port 8778 #677

### LINKED ISSUE #677: KarafGenerator misses jolokia port 8778
### Info

* Eclipse JKube version :1.2.0
* Maven version (`mvn -v`) :
```
3.6.3
```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :

When building a Karaf based image with jkube plugin, there is no jolokia port 8778 in the auto-generated deploymentconfig.yml. But the jolokia port 8778 is important for Karaf based image, since other App like Fuse Console need to talk to jolokia agent via jolokia port
* Sample Reproducer Project : *[GitHub Clone URL]*

### PR DESCRIPTION
**Pull request by ffang**
## Description
Fix  #677

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by ffang** [comment]
Hi @rohanKanojia,

Is this OK to merge? I saw test failure in CI but I guess it's random? (I didn't see test failure before I add Signed-Off footer).

Thanks!
Freeman

**Comment by rohanKanojia** [comment]
I've restarted the workflow

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
Tests won't pass since Karaf Deployment ports are checked:
```
Error:  Failures: 
Error:    KarafK8sITCase.K8sApply:110 
Expected: (a collection containing (hasProperty("image", "integration-tests/karaf-camel-log:latest") and hasProperty("name", "karaf") and hasProperty("ports", a collection with size <1>) and hasProperty("ports", (a collection containing (hasProperty("name", "intermapper") and hasProperty("containerPort", <8181>))))))
     but: a collection containing (hasProperty("image", "integration-tests/karaf-camel-log:latest") and hasProperty("name", "karaf") and hasProperty("ports", a collection with size <1>) and hasProperty("ports", (a collection containing (hasProperty("name", "intermapper") and hasProperty("containerPort", <8181>))))) mismatches were: [hasProperty("ports", a collection with size <1>) property 'ports' collection size was <2>]
```

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by manusa** [comment]
https://github.com/jkubeio/jkube-integration-tests/pull/83

**Comment by ffang** [comment]
Thanks @manusa !

**Pull request merged**
