### PR TITLE
fix: ClassCastException when extracting plugins

### LINKED ISSUE #2093: ClasscastException in kubernetes-maven-plugin
### Describe the bug

I run into the following exception with the maven-kubernetes-plugin:

```
> mvn -e clean install
...
rg.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.11.0:build (docker-build-app) on project kubernetes-sample: A type incompatibility occurred while executing org.eclipse.jkube:kubernetes-maven
-plugin:1.11.0:build: class java.util.HashMap cannot be cast to class java.lang.String (java.util.HashMap and java.lang.String are in module java.base of loader 'bootstrap')
...
Caused by: java.lang.ClassCastException: class java.util.HashMap cannot be cast to class java.lang.String (java.util.HashMap and java.lang.String are in module java.base of loader 'bootstrap')
    at org.eclipse.jkube.kit.common.util.MavenConfigurationExtractor.addAsList (MavenConfigurationExtractor.java:73)
    at org.eclipse.jkube.kit.common.util.MavenConfigurationExtractor.getElement (MavenConfigurationExtractor.java:54)
    at org.eclipse.jkube.kit.common.util.MavenConfigurationExtractor.getElement (MavenConfigurationExtractor.java:59)
    at org.eclipse.jkube.kit.common.util.MavenConfigurationExtractor.getElement (MavenConfigurationExtractor.java:59)
    at org.eclipse.jkube.kit.common.util.MavenConfigurationExtractor.getElement (MavenConfigurationExtractor.java:59)
    at org.eclipse.jkube.kit.common.util.MavenConfigurationExtractor.extract (MavenConfigurationExtractor.java:41)
    at org.eclipse.jkube.kit.common.util.MavenUtil.getPlugins (MavenUtil.java:73)
    at org.eclipse.jkube.kit.common.util.MavenUtil.convertMavenProjectToJKubeProject (MavenUtil.java:205)
    at org.eclipse.jkube.maven.plugin.mojo.build.AbstractDockerMojo.doExecute (AbstractDockerMojo.java:434)
    at org.eclipse.jkube.maven.plugin.mojo.build.AbstractDockerMojo.execute (AbstractDockerMojo.java:413)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

```
Maven-Version:
```
> mvn -v
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\ProgrammeDE\Java\tools\apache-maven-3.8.6
Java version: 17.0.4, vendor: Eclipse Adoptium, runtime: C:\ProgrammeDE\Java\jdk17.0.4_8-win64
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

```

### Eclipse JKube version

1.11.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

1. Add the following maven plugin to pom.xml that has also the kubernetes-maven-plugin configured
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-checkstyle-plugin</artifactId>
        <version>3.2.1</version>
	<configuration>
		<checkstyleRules>
			<module name="Checker">
				<module name="TreeWalker">
					<module name="IllegalImport">
						<property name="severity" value="warning" />
						<property name="illegalPkgs" value="sun, edu"/>
					</module>

					<module name="RedundantImport"/>
				</module>
			</module>
		</checkstyleRules>
		....
	</configuration>
</plugin>
```
2. Run `mvn install`

The `<module name="RedundantImport"/>`  causes the exception. When I change it to 
```
<module name="RedundantImport">
     <property name="severity" value="warning" />
</module>
```
then the exception does no longer occur.

### Expected behavior

The configuration of the checkstyle-maven-plugin is a valid Maven configuration.
The kubernetes-maven-plugin should work with such a configuration

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Windows

### Eclipse JKube Logs

_No response_

### Sample Reproducer Project

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PavelItel228**
## Description

Fixes #2093

Description: 
When the elements in pom.xml are in a list, and one of them has internal elements and the other does not(see code below), then we get a ClassCastException because the code does not know how to work with HashMap. Handling this situation also does not make sense, because the 2nd element does not contain anything inside, therefore we have nothing to add to the first element.

```
<module name="TreeWalker">
    <module name="IllegalImport">
        <property name="severity" value="warning"/>
        <property name="illegalPkgs" value="sun, edu"/>
    </module>

    <module name="RedundantImport"/>
</module>
```

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@PavelItel228 : Thanks for your PR. Do you think we can add some sort of test to verify this fix?

**Comment by PavelItel228** [comment]
> @PavelItel228 : Thanks for your PR. Do you think we can add some sort of test to verify this fix?

@rohanKanojia Yes, sure

**Review by rohanKanojia — APPROVED** [review]

**Comment by PavelItel228** [comment]
> @PavelItel228 : Thanks, your changes look good to me. Could you please add a line about them in CHANGELOG.md file?

@rohanKanojia : Thanks, added

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
