### PR TITLE
#2874 update `vertx.version` in pom.xml

### LINKED ISSUE #2874: Quickstarts (quickstarts/maven/vertx4) : Bump `vertx.version` to latest version
### Component

None

### Description

Our current vertx4 quickstart seems to be using slightly older version of vertex
https://github.com/eclipse/jkube/blob/335aa3bcd76523c4f9ee89dab46225278b3ce20d/quickstarts/maven/vertx4/pom.xml#L37

We should update it to latest available version (4.5.7 at the time of creating the issue)

### Expected Behavior
Vertx version is bumped to latest version

### Acceptance Criteria
- [x] Vertx version is bumped to latest available release
- [x] Quickstart works as expected as defined in its [README](https://github.com/eclipse/jkube/blob/335aa3bcd76523c4f9ee89dab46225278b3ce20d/quickstarts/maven/vertx4/README.md)

### PR DESCRIPTION
**Pull request by anglerfishlyy**
Fix #2874

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2879 (_2024-04-05T14:50:45Z_)

:gear: [JKube E2E Tests (8571659047)](https://github.com/jkubeio/ci/actions/runs/8571659047) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2879)](https://github.com/jkubeio/ci/actions/runs/8571659047/job/23492413686)

**Comment by rohanKanojia** [comment]
@anglerfishlyy Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff

# push changes again
git push origin yourbranchname -f
```

**Comment by anglerfishlyy** [comment]
sir , i did create an  account on Eclipse.but i am unable to access it after trying to change password.
I tried  contacting  ***@***.*** ***@***.***> but nothing happened.
________________________________

**Comment by anglerfishlyy** [comment]
Hello sir ,
May i know what's the issue with this?

**Comment by rohanKanojia** [comment]
@anglerfishlyy : Hello, I see you're contributing for the first time. This issue was created for people who have already contributed to the project.

Apart from making changes in `pom.xml` you also need to test that quickstart works on Kubernetes and OpenShift.

**Comment by anglerfishlyy** [comment]
I will be learning soon.
Thank you for your time ,sir.
________________________________

**Pull request closed without merging**
