### PR TITLE
Issue Fix #2601 : Fix windows tests in `jkube-kit/build/api` module

### LINKED ISSUE #2601: Fix `jkube-kit/build/api` module's unit tests on Windows
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/1338

:warning: A windows machine is required to reproduce and fix problems in this issue.

When running `mvn clean install` on Windows, I see the following tests failing in `jkube-kit/build/api` module:

- [DockerFileUtilTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java)
- [AssemblyManagerCreateDockerTarArchiveTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerCreateDockerTarArchiveTest.java)
- [OpenShiftRegistryAuthHandlerTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandlerTest.java)

### Expected Behavior
`mvn clean install` should pass with all tests on `jkube-kit/build/api`

### Acceptance Criteria
- [x] `jkube-kit/build/api` module's build passes on windows

### PR DESCRIPTION
**Pull request by l3002**
## Description

Fixes #2601

Modified all the unit tests failing for Windows during the execution of `mvn clean install`.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2629 (_2024-02-07T11:41:39Z_)

:gear: [JKube E2E Tests (7814210215)](https://github.com/jkubeio/ci/actions/runs/7814210215) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2629)](https://github.com/jkubeio/ci/actions/runs/7814210215/job/21314983493)

**Comment by rohanKanojia** [comment]
@l3002 : Was `jkube-kit/build/api` module building successfully after making these changes?

**Comment by l3002** [comment]
@rohanKanojia : yeah, it was building successfully after the given changes. Though a few tests are still failing in `jkube-kit/build/service` module. Here's a screenshot for your reference

Screenshot 2024-02-08 124307

**Comment by rohanKanojia** [comment]
@l3002 : I've created https://github.com/eclipse/jkube/issues/2640 for those failures

**Comment by l3002** [comment]
@rohanKanojia, Do you mind if I pick #2640 up? Or Have you already planned on assigning it to someone else?

I am already trying to figure out the cause of that issue.

**Comment by rohanKanojia** [comment]
@l3002 : I haven't checked what's the root cause of the failure, 

> Do you mind if I pick https://github.com/eclipse/jkube/issues/2640 up? Or Have you already planned on assigning it to someone else?

sure, you can pick it up. Just add a comment that you want to work on it.

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Pull request merged**
