### PR TITLE
Feature #658: Apply configuration in DependencyEnricher

### PR DESCRIPTION
**Pull request by rnetuka**
Solution for #658 

Current solution is for replica count only. If you have any tips what to add, just let me know.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Thanks a lot for your PR :+1: . Could you please add a test to verify that provided fix works as per our expectations?

**Comment by rnetuka** [comment]
Amendments:
1. Test case added
2. /jkube-kit/enricher/generic/src/test/resources/jenkins-4.0.41.jar!/META-INF contains **fabric8** directory instead of **jkube**. I've added a fix for that (I hope it works this way since GitHub won't show me the changes...)
3. Inside the new function `item` could be any of `Deployment`, `DeploymentConfig`, `DeploymentBuilder` and `DeploymentConfigBuilder`. The _if-else_ plus _cast_ is extremely ugly, so any tips how to make it better are welcome

**Comment by rnetuka** [comment]
Replaced by https://github.com/eclipse/jkube/pull/675

**Pull request closed without merging**
