### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codezork**
Added 'Troubleshooting' sharing minikube's docker env

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Thanks for your quick PR :+1: . In order to be able to merge your PR, you need to sign-off your commit with an e-mail account belonging to a user who has signed the Eclipse Contributor Agreement.

More details: https://www.eclipse.org/jkube/contributing#legal

**Comment by manusa** [comment]
Relates to #150

**Comment by codezork** [comment]
can I also set signoff from the ui? I didn't check out for the readme change.

Shouldn't we change the pom.xml to version "1.0.0-alpha-1" for at least in helloworld?

**Comment by rohanKanojia** [comment]
I think you would need to create an eclipse account to be able to sign ECA. Actually all of our quickstarts are at SNAPSHOT  version right now. @manusa What do you think about setting quickstarts version to latest release rather than SNAPSHOTS?

**Comment by manusa** [comment]
> can I also set signoff from the ui? I didn't check out for the readme change.

Sign off is just an extra-line in the commit message with the format "Signed-off-by: Your Name <email@example.com>

> Shouldn't we change the pom.xml to version "1.0.0-alpha-1" for at least in helloworld?

Versions in Quickstarts are modified using a script so that they all have the same version, usually this is done upon release and tag.

`./scripts/quickstarts.sh version`

The project is currently under very active development, so we committed an extra change to point quickstarts back to SNAPSHOT.

I really don't know if there are many users now, depending on that it may be helpful to change quickstarts version back to current release.

**Comment by rohanKanojia** [comment]
@codezork : ah, not sure why PR got closed on update :broken_heart: . Could you please create a separate PR with the corrected email which is a registered Eclipse account?

I admit it's a bit frustrating to deal with ECA :-(

**Pull request closed without merging**
