### PR TITLE
fix: JIB assembly works on Windows

### PR DESCRIPTION
**Pull request by manusa**
## Description
Fix: #705 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
JIB build model is working fine on my machine

**Comment by rohanKanojia** [comment]
Umm, sorry could you please provide some context? I see you moved `getAssemblyTarArchive` call below . How does this fix this issue?

**Comment by manusa** [comment]
> Umm, sorry could you please provide some context? I see you moved `getAssemblyTarArchive` call below . How does this fix this issue?

Yes, sorry.

For the JIB assembly process we do something quite ugly since we need to reuse part of what is done for the Docker assembly process and those methods weren't designed with reusability in mind (hence the relation of #705 with #300).

The problem is that we are copying twice the files to the destination temporary directory and in Windows, when the Jar artifact is "replaced" there is an error since for some reason it gets loaded in memory. The current approach is just a quick fix, the proper fix should be implemented in scope of #300. We already did some progress in that area, and probably the double copy approach call should no longer be necessary. However, there are still some procedures run in the `getAssemblyTarArchive` method which aren't externalized, so maybe it's not a good idea to completely remove/replace that call yet.

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
