### PR TITLE
Update the version of micronaut

### LINKED ISSUE #2753: Quickstarts : Update Micronaut version in `quickstarts/maven/micronaut`
### Component

None

### Description

Our Micronaut quickstarts are using an outdated version of [Micronaut framework](https://micronaut.io/):

https://github.com/eclipse/jkube/blob/3afc7bf1f8dbe4452826c5ec7ec58de5c9408d53/quickstarts/maven/micronaut/pom.xml#L24
https://github.com/eclipse/jkube/blob/3afc7bf1f8dbe4452826c5ec7ec58de5c9408d53/quickstarts/maven/micronaut-customized-image/pom.xml#L24

Micronaut 4 now requires Java 17 as baseline. Maybe we should not update this quickstart directly to 4.x. For now, updating it to the latest 3.x version (`3.9.7` at the time of creating this issue) would be okay.

:warning: This requires setting up some local Kubernetes Cluster ([MiniKube](https://minikube.sigs.k8s.io/docs/start/)/[Kind](https://kind.sigs.k8s.io/))

After updating Micronaut version, you should verify that quickstart is building fine and is also working as specified in their respective [README](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/micronaut-customized-image/README.md) . You can take a look at this YouTube video [Sprint 192 - Eclipse JKube Micronaut integration](https://youtu.be/I3pjd0D90gA) to see how to try it out.

### Expected Behavior
Micronaut Quickstart is updated to latest `3.x` version

### Acceptance Criteria
- [ ] Micronaut Quickstarts are updated to latest `3.x` version
- [ ] Micronaut Quickstarts work as documented in their respective README.md files

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by clarenced**
## Description

Update of to the latest 3.9.x version of micronaut
Fixes #2753

## Type of change

 - [x] Breaking change (fix or feature that would cause existing functionality to change

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] Micronaut Quickstarts are updated to latest 3.x version
 - [x] Micronaut Quickstarts work as documented in their respective README.md files

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2770 (_2024-03-05T14:24:25Z_)

:gear: [JKube E2E Tests (8157858710)](https://github.com/jkubeio/ci/actions/runs/8157858710) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2770)](https://github.com/jkubeio/ci/actions/runs/8157858710/job/22298444990)

**Comment by rohanKanojia** [comment]
@clarenced : Have you tested the quickstart by deploying it to some minikube cluster like this Video [Sprint 192 - Eclipse JKube Micronaut integration](https://youtu.be/I3pjd0D90gA)

**Comment by clarenced** [comment]
@rohanKanojia Actually, this is what I am testing right now. I have this error when trying to deploy on minikube : 
```
 Warning  Failed     17m (x4 over 19m)    kubelet            Failed to pull image "maven/micronaut:1.16.1": Error response from daemon: pull access denied for maven/micronaut, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed     17m (x4 over 19m)    kubelet            Error: ErrImagePull
  Warning  Failed     17m (x6 over 19m)    kubelet            Error: ImagePullBackOff
```

**Comment by clarenced** [comment]
Hi @rohanKanojia , I had an issue while deploying the application to minikube. I have finally fixed it.

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
