### PR TITLE
Fix #835: KubernetesResourceTask: KubernetesExtension has required configuration options

### LINKED ISSUE #835: KubernetesResourceTask: KubernetesExtension has required configuration options
## Description

Child of #31 

KubernetesResourceTask can be configured

## AC
- [x] KubernetesExtension has a `getPlatformMode()` method that returns `kubernetes`
- [x] OpenShiftExtension extends `getPlatformMode()` method and returns `openshift`
- [x] KubernetesExtension has a `resourceTargetDirectory` field (`Property<File>`) to specify the YAML resource generation output
  - Defaults to `${build.classes.directory}/META-INF/jkube`
- [x] KubernetesExtension has a `resourceSourceDirectory` field (`Property<File>`) to specify the directory where source fragments can be found
  - Defaults to `${basedir}/src/main/jkube`
- [x] KubernetesExtension has a `resourceEnvironment` field (`Property<String>`) to specify the environment directory (dev, prod, etc.) where source fragments can be found (if not blank)
- [x] KubernetesExtension has a `useProjectClasspath` field (`Property<Boolean>`) to specify if JKube should search for additional enrichers/generators in the project's classpath
  - Defaults to `false`
- [x] KubernetesExtension has a `workDirectory` field (`Property<File>`) to specify the directory JKube uses for temporary file generation and work.
- [x] KubernetesExtension has a `skipResourceValidation` field (`Property<Boolean>`) that enables/disable ResourceValidation
  - Defaults to `false`
- [x] KubernetesExtension has a `failOnValidationError` field (`Property<Boolean>`) that causes resource generation to fail in case the generated resources are invalid
  - Defaults to `false`
- [x] KubernetesExtension has a `resources` field (`ResourceConfig`)
- [x] KubernetesExtension has a `profile` field (`Property<String>`) to enable the usage of a specific profile
- [x] KubernetesExtension has a `enricher` field (`ProcessorConfig`) to allow the configuration of Enrichers
- [x] KubernetesExtension has a `generator` field (`ProcessorConfig`) to allow the configuration of Generators
- [x] KubernetesExtension has a `mappings` field (`List<MappingConfig>`) that allows overriding the default fileName Resource type mappings
- [x] KubernetesExtension has a `namespace` field (`Property<String>`) that overrides ResourceConfig#namespace if present (not blank)
- [x] KubernetesExtension has a `resourceFileType` field (`Property<ResourceFileType>`) to allow the type of resource files to be generated (YAML / JSON)
  - Defaults to `yaml`
- [x] KubernetesExtension has a `mergeWithDekorate` field (`Property<Boolean>`) to enable the Dekorate resource merge experimental feature
  - Defaults to `false`
- [x] KubernetesExtension has a `interpolateTemplateParameters` field (`Property<Boolean>`) to allow enabling/disabling template placeholder interpolation
  - Defaults to `true`
- [x] KubernetesResourceTask overrides initJKubeServiceHubBuilder to provide a resourceService configuration
- [x] Create a profiles-default.yml file in `gradle-plugin/kubernets/src/main/resources/META-INF/jkube` with the same content found in the KubernetesMavenPlugin equivalent
- [x] Create a profiles-default.yml file in `gradle-plugin/openshift/src/main/resources/META-INF/jkube` with the same content found in the OpenShiftMavenPlugin equivalent

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Relates to #835

Add configuration options to KubernetesExtension required for
KubernetesResourceTask

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Hi, these fields seem to have been added in KubernetesExtension in this PR:
- resourceTargetDirectory
- resourceSourceDirectory
- useProjectClassPath
- failOnValidation(typo, should be renamed to failOnValidationError)
- mergeWithDekorate
- interpolateTemplateParameters

Is there some specific reason they are marked as unchecked in issue description?

**Comment by rohanKanojia** [comment]
I thought `getOrElse(...)` was doing this. If it's not clean enough, Do you want additional methods which will wrap around `getOrElse(...)` and return default value if it's null?

**Comment by manusa** [comment]
There's no getOrElse in this PR.

For the default values, create getters such as [getResourceFileType](https://github.com/eclipse/jkube/blob/1455004ec141cbeade0ccb749f37775ccbd5efaa/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java#L191), where you actually perform the getOrElse. This way we keep the defaults and properties centralized (i.e. next step will be resolving properties here too.)

**Pull request merged**
