### PR TITLE
SIMPLE-FIELD-TYPES Changed To Private

### PR DESCRIPTION
**Pull request by skpandey885**
ISSUE NO. #746 
SIMPLE FIELD TYPES Changed To Private!

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Comment by skpandey885** [comment]
> Welcome, Thanks a lot for contributing to Eclipse JKube 👍,
> 
> In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
> 
> ```
> # (Optional): Configure Git User and Email
> git config user.name "Your Name"
> git config user.email "your_email@example.com"
> 
> # Amend your previous commit with signed off footer
> git commit --amend --signoff
> ```

Can You Explain a bit about how to sign off?

**Comment by rohanKanojia** [comment]
You just need to copy-paste the commands I linked with your replaced email/username in previous message in your project directory.

**Comment by skpandey885** [comment]
How long Will It Take To get merged?

**Comment by rohanKanojia** [comment]
@skpandey885: You still need to fix ECA check by adding signed-off-by footer. Note that email used in footer must be same as the email you used for creating Eclipse Account.

**Comment by skpandey885** [comment]
> @skpandey885: You still need to fix ECA check by adding signed-off-by footer. Note that email used in footer must be same as the email you used for creating Eclipse Account.

Yeah I done those commands in my repo! so how long now will it take to get merged?

**Comment by rohanKanojia** [comment]
You need to push the updated branch to github as well.
```
git push origin Make-SIMPLE-FIELD-TYPES-private -f
```

**Comment by skpandey885** [comment]
> You need to push the updated branch to github as well.
> 
> ```
> git push origin Make-SIMPLE-FIELD-TYPES-private -f
> ```

yeah I did it showing "EVERYTHING IS UPTO DATE"

**Comment by manusa** [comment]
Hi @skpandey885 

Your current commit (7a9e7e03) is authored by `skpandey885 <sachin@sachins-macbook-air.local>`.

This is a local e-mail address which I seriously doubt you used to sign Eclipse's ECA.

You should follow the procedure Rohan suggested in his [comment](https://github.com/eclipse/jkube/pull/761#issuecomment-873824874). And then force-push your branch (`git push origin Make-SIMPLE-FIELD-TYPES-private -f`).

If everything goes well, your commit will look like
```
SIMPLE-FIELD-TYPES Changed To Private

Signed-off-by: Sachin Pandey <email-that-signed-the-eca@examplecom>
```

And a message similar to:
```
@skpandey885 skpandey885 force-pushed the skpandey885:Make-SIMPLE-FIELD-TYPES-private branch from xxxyyyzzz to zzzyyyxxx 1 minute ago
```

Will be visible in this PR

**Comment by skpandey885** [comment]
> Hi @skpandey885
> 
> Your current commit ([7a9e7e0](https://github.com/eclipse/jkube/commit/7a9e7e034230f56127254b5311ea1ab1133744ed)) is authored by `skpandey885 <sachin@sachins-macbook-air.local>`.
> 
> This is a local e-mail address which I seriously doubt you used to sign Eclipse's ECA.
> 
> You should follow the procedure Rohan suggested in his [comment](https://github.com/eclipse/jkube/pull/761#issuecomment-873824874). And then force-push your branch (`git push origin Make-SIMPLE-FIELD-TYPES-private -f`).
> 
> If everything goes well, your commit will look like
> 
> ```
> SIMPLE-FIELD-TYPES Changed To Private
> 
> Signed-off-by: Sachin Pandey <email-that-signed-the-eca@examplecom>
> ```
> 
> And a message similar to:
> 
> ```
> @skpandey885 skpandey885 force-pushed the skpandey885:Make-SIMPLE-FIELD-TYPES-private branch from xxxyyyzzz to zzzyyyxxx 1 minute ago
> ```
> 
> Will be visible in this PR

Hey I Did All The Things! Can You Tell Me When My PR Will Get Merged?

**Comment by rohanKanojia** [comment]
@skpandey885: Are you sure that you've updated PR as per the suggested changes? I'm sorry if we're not explaining ourselves clearly. Your changed need to be pushed to github too so that we can see. We haven't seen any update :+1: 
Screenshot from 2021-07-05 20-30-02

**Comment by rohanKanojia** [comment]
> Hey I Did All The Things! Can You Tell Me When My PR Will Get Merged?

@skpandey885 : Your PR will be merged whenever you update it as per suggested changes. We're waiting for you to update this pull request.

**Comment by skpandey885** [comment]
> > Hey I Did All The Things! Can You Tell Me When My PR Will Get Merged?
> 
> @skpandey885: Your PR will be merged whenever you update it as per suggested changes. We're waiting for you to update this pull request.

How To Update It! Everything Is Done!
Can You Tell Me Steps From The Beginning Then I'll Delete This PR And Generate a New One! Or What should I do! Please Guide Me!

**Comment by skpandey885** [comment]
After Signed Off Thing! What I've To Do?

**Review by manusa — APPROVED** [review]

**Pull request merged**
