### PR TITLE
feat (jkube-kit/resource) : Adds condition to HelmDependency

### PR DESCRIPTION
**Pull request by bryopsida**
## Description

Adds `condition`, and `alias` properties to the `HelmDependency`. For more information on `condition` see [here](https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies), and [here](https://helm.sh/docs/topics/charts/#alias-field-in-dependencies) for `alias`.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@bryopsida : Thanks for your PR! Could you please add some documentation about these fields in https://github.com/eclipse/jkube/blob/master/jkube-kit/doc/src/main/asciidoc/inc/helm/_jkube_helm.adoc ?

Also, Could you please add a line to CHANGELOG.md about this change?

**Review by manusa — APPROVED** [review]
Please check Rohan's comments, otherwise looks good, thx!

**Review by sunix — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by bryopsida** [comment]
Is there anything I need to do on my end to resolve the ci checks? Looks like a failure to pull a maven artifact based on the logs.

**Comment by rohanKanojia** [comment]
@bryopsida : Could you please try rebasing your branch and force push again to retrigger builds?

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
