### PR TITLE
Issue fix #2811 chore (quickstarts/maven/quarkus-customized-image): Updated to latest version of Quarkus 

### LINKED ISSUE #2811: Update `quickstarts/maven/quarkus-customized-image` to latest version
### Component

None

### Task description

Our quickstarts/maven/quarkus is using a slightly old version of Quarkus. It should be updated to the latest version (`3.8.2` at the time of writing)

https://github.com/eclipse/jkube/blob/c4ee9d4e9432297c50d9385a8c06d1fea0f75e3a/quickstarts/maven/quarkus-customized-image/pom.xml#L37

After changing the version, you might face problems regarding missing imports. They just need to be moved to `jakarta` package instead:
- `javax.ws.rs.GET` -> `jakarta.ws.rs.GET`
- `javax.inject.Singleton` -> `jakarta.inject.Singleton`

:warning: A Kubernetes Cluster is required to test that JKube's Kubernetes Maven Plugin can deploy application to Kubernetes cluster

### Expected Behavior
Quarkus quickstart is updated to latest version

### Acceptance Criteria
- [x] Quarkus quickstart builds successfully after version bump
- [ ] Quickstart is tested on a Kubernetes cluster to verify it's working as documented in README.md

### PR DESCRIPTION
**Pull request by l3002**
## Description

Fixes #2811 

Updated `Quarkus` version to `3.9.1` and fixed all the breaking imports.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2865 (_2024-04-01T05:28:08Z_)

:gear: [JKube E2E Tests (8504274069)](https://github.com/jkubeio/ci/actions/runs/8504274069) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2865)](https://github.com/jkubeio/ci/actions/runs/8504274069/job/23290936535)

**Review by rohanKanojia — APPROVED** [review]

**Comment by l3002** [comment]
@rohanKanojia: Just wanted to let you know, I don't have openshift cluster setup, therefore I was not able to test `quarkus-customized-image`.

**Comment by rohanKanojia** [comment]
@l3002 : Did you try creating account on https://developers.redhat.com/developer-sandbox ?

**Comment by l3002** [comment]
> @l3002 : Did you try creating account on https://developers.redhat.com/developer-sandbox ?

@rohanKanojia : No, Would it provide a free tier for `oc`?

**Comment by rohanKanojia** [comment]
@l3002 : Yes, you should be able to create a free cluster (No credit card required). I use it for testing.

**Comment by l3002** [comment]
@rohanKanojia : Great I'll check it out.

**Review by sunix — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by manusa** [comment]
The quickstart is no longer working due to an incompatible base image. I'll send a PR to fix it.

**Comment by gbraad** [comment]
> incompatible base image.

:-/

**Pull request merged**
