### PR TITLE
Fixed issue#1865

### LINKED ISSUE #1865: [Hacktoberfest] ResourceFileType fields may be 'final'
### Description
The following statement is reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/ec6e446c24e1da97dbde1d0f21f720f6b98bd53d/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/ResourceFileType.java#L47
 
- [x] should be changed to:
```java
    private final String artifactType;
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by javamultiplex**
closes #1865

### CODE REVIEW

**Comment by javamultiplex** [comment]
@manusa - I have fixed issue#1865, you can review now.

**Comment by rohanKanojia** [comment]
@javamultiplex : ECA check seems to be failing. Are you sure you have created Eclipse Account and singed off ECA?

**Comment by javamultiplex** [comment]
> @javamultiplex : ECA check seems to be failing. Are you sure you have created Eclipse Account and singed off ECA?

It is passed now, I have created Eclipse Account and signed off ECA

**Review by rohanKanojia — APPROVED** [review]

**Comment by javamultiplex** [comment]
@manusa / @rohanKanojia  - If the changes look fine can you please merge the PR

**Comment by manusa** [comment]
Hi @javamultiplex 
Any reason why you closed the PR?

**Comment by javamultiplex** [comment]
@manusa - By mistake I deleted the forked repository, I thought PR merged but it was open.  Let me fix it

**Comment by javamultiplex** [comment]
Re-opening PR as it was closed by mistake.

**Review by manusa — APPROVED** [review]

**Pull request merged**
