### PR TITLE
spike Jenkins jobs

### PR DESCRIPTION
**Pull request by manusa**
## Description

Part of #2069 

- ci: replace CircleCI Javadoc job with Jenkins
- ci: replace CircleCI Sonar (PR) job with Jenkins

Tasks:
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3376
- https://github.com/eclipse-cbi/jiro/pull/286

References:
- https://wiki.eclipse.org/Jenkins#GitHub_Branch_Source_Plugin
- https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-controllers/github-webhook-pipeline-multibranch

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
> How would failures on jenkins reported on PR?

Still verifying that, there's a check, but it doesn't show a nice description:
image

**Comment by rohanKanojia** [comment]
ohk, did this require additional configuration on Jenkins side? I think if this works we can switch all CircleCI pipelines to Jenkins :+1:

**Comment by manusa** [comment]
> ohk, did this require additional configuration on Jenkins side? I think if this works we can switch all CircleCI pipelines to Jenkins +1

It requires a special job configuration, however, if we have multiple jobs it might not look good since the check name is vague and generic

**Comment by rohanKanojia** [comment]
I think it should be possible to configure this. We should check with Eclipse Admin team .

**Comment by manusa** [comment]
> I think it should be possible to configure this. We should check with Eclipse Admin team .

Needs a different plugin which I think is not available. Anyway, I'm still testing stuff. The WebHook doesn't seem to work.

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
Everything is working as expected now, seems like this can be a good replacement for CircleCI.
I'll merge this PR before continuing with the rest of the migration. I want to see how does the plugin behave upon merge.

**Pull request merged**
