### PR TITLE
typo in readme

### PR DESCRIPTION
**Pull request by survivant**
typo

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@survivant :  Thanks for checking out the project and contributing. In order to be able to merge your PR, you need to sign-off your commit with an e-mail account belonging to a user who has signed the Eclipse Contributor Agreement.

More details: https://www.eclipse.org/jkube/contributing#legal

**Comment by survivant** [comment]
I just sign the ECA.  DO I need to do something else ?

**Comment by rohanKanojia** [comment]
Is you commit signed off with the email associated with your Eclipse Account?

**Comment by survivant** [comment]
> Is your commit signed off with the email associated with your Eclipse Account?

yes.  maybe a have to create another commit with

git commit -s -m "with signoff now" ?

**Comment by rohanKanojia** [comment]
You cal do `git commit --amend` and force push with a format like this:
```
commit e6fd4a3bcdb5f0fd7391a729a4707afed57e1bc8
Author: Rodney Russ <rdruss@gmail.com>
Date:   Wed Mar 18 15:29:05 2020 -0600

    Fix PascalCase for OpenShift
    
    Signed-off-by: Rodney <rdruss@gmail.com>

```

**Comment by rohanKanojia** [comment]
ah, I didn't notice that you ECA check was still red :man_facepalming:

**Comment by rohanKanojia** [comment]
@waynebeaton : Hi, Is it possible to change repository configuration to make ECA check required for merging? I accidentally merged this PR without ECA being green and would like to avoid situations like these in the future.

Would appreciate if you could provide some input.

**Comment by waynebeaton** [comment]
Do you mean blocking? If that's what you want, open an issue against Community/GitHub in the Eclipse Bugzilla instance with your request. By way of expectation management, many other project teams will not want this.

**Comment by rohanKanojia** [comment]
Sorry for naive question, Do you mean that ECA is not a hard check? Are other teams also working with current workflow(with ECA check being optional)? I was afraid that we might run into issues after merging this PR.

**Comment by waynebeaton** [comment]
Committers are responsible for implementing the Eclipse Foundation's IP Policy. The ECA checker is there to help committers with that task. The ECA checker generally gets it right, but does occasionally get in the way. In those cases, we expect the project team to do the right thing (with care). It would also be helpful if you report when the ECA checker gets it wrong so that we can try to address them and make the tool more useful.

Frankly, I'm not fussed about the intellectual property management concerns around a single character being added to a YAML file to fix a typo. That you merged it by accident raises some concern, but I'm pretty convinced that you're unlikely to do that again. :-)

**Pull request merged**
