### PR TITLE
Upgrade build environment of sonar jobs on CircleCI

### LINKED ISSUE #558: Upgrade Sonar CircleCI job to Java 11
Hi,

Is there any roadmap for this project to bump support to `JDK 11`.

I have been studying this project for a few days and found out that this Project is using [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube&branch=master) for Static Code analysis.
SonarCloud is set to **[phase out](https://sonarcloud.io/documentation/appendices/end-of-support/)** `JDK 8` support in favour of `JDK 11` **1st February, 2021.**

</br>

I will be very keen to help migrate this project to JDK 11 along with the GitHub Actions pipelines as well.

### PR DESCRIPTION
**Pull request by ohbus**
## Description

- [x] Upgraded CircleCI to use JDK 11
- [x] Should fix #558 
- [x] Updated to `docker` based environment from `machine`

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [x] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Seems like `ThorntailV2HealthCheckEnricherTest` is failing on JDK11. I've seen this failure myself while working with JDK11. Maybe we should refactor/remove it.

```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ThorntailV2HealthCheckEnricherTest.setUp:67 » ClassCast class jdk.internal.loa...
[ERROR]   ThorntailV2HealthCheckEnricherTest.setUp:67 » IllegalArgument Value of type or...
[ERROR]   ThorntailV2HealthCheckEnricherTest.setUp:67 » IllegalArgument Value of type or...
[ERROR]   ThorntailV2HealthCheckEnricherTest.setUp:67 » IllegalArgument Value of type or...
```

**Comment by manusa** [comment]
I'll take a look

**Comment by rohanKanojia** [comment]
ohk, Thanks a lot!

**Comment by ohbus** [comment]
> Seems like `ThorntailV2HealthCheckEnricherTest` is failing on JDK11. I've seen this failure myself while working with JDK11. Maybe we should refactor/remove it.
> 
> ```
> [INFO] Results:
> [INFO] 
> [ERROR] Errors: 
> [ERROR]   ThorntailV2HealthCheckEnricherTest.setUp:67 » ClassCast class jdk.internal.loa...
> [ERROR]   ThorntailV2HealthCheckEnricherTest.setUp:67 » IllegalArgument Value of type or...
> [ERROR]   ThorntailV2HealthCheckEnricherTest.setUp:67 » IllegalArgument Value of type or...
> [ERROR]   ThorntailV2HealthCheckEnricherTest.setUp:67 » IllegalArgument Value of type or...
> ```

I believe for the same reason I was not able to build the project on my local system, as I am also using JDK 11.

But the GitHub Actions jobs I suppose are all on JDK 11 right?

You may raise an issue regarding this and mention me, so that I can take a look at it to see if I can lend some helping hand.

Thanks.

**Comment by manusa** [comment]
> I believe for the same reason I was not able to build the project on my local system, as I am also using JDK 11.
> 
> But the GitHub Actions jobs I suppose are all on JDK 11 right?
> 
> You may raise an issue regarding this and mention me, so that I can take a look at it to see if I can lend some helping hand.
> 
> Thanks.

GitHub actions are on 11, but are only compiling the project (no unit tests are run).

These actions are used for e2e tests that are hosted in https://github.com/jkubeio/jkube-integration-tests/

I already created a PR with a fix #563. Once it's merged, you'll have to rebase your PR onto master and hopefully tests will be passing then and we'll be able to merge yours.

**Review by manusa — APPROVED** [review]
LGTM, thank you very much for your contribution!

**Pull request merged**
