### PR TITLE
ContainerHandler : Return empty collection instead of null

### LINKED ISSUE #2812: ContainerHandler : Return empty collection instead of `null`
### Component

JKube Kit

### Description
ContainerHandler seems to be returning a null value in a method with a list return type:

https://github.com/eclipse/jkube/blob/c4ee9d4e9432297c50d9385a8c06d1fea0f75e3a/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandler.java#L184

Sonar flags this as a code smell. We should replace this with `Collections.emptyList()`.

Expectations would also need to be updated in ContainerHandlerTest 

### Expected Behavior
ContainerHandler.getContainerPorts is updated to return a non null value

### Acceptance Criteria
- [ ] ContainerHandler.getContainerPorts is updated to return a non null value
- [ ] Project compiles successfully after running `mvn clean install`

### PR DESCRIPTION
**Pull request by MayankMadan97**
Fixes #2812 

## Type of change
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

Acceptance Criteria (From Bug description)

 - [x] ContainerHandler.getContainerPorts is updated to return a non null value
 - [x] Project compiles successfully after running mvn clean install

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2822 (_2024-03-15T04:50:47Z_)

:gear: [JKube E2E Tests (8291462362)](https://github.com/jkubeio/ci/actions/runs/8291462362) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2822)](https://github.com/jkubeio/ci/actions/runs/8291462362/job/22691207584)

**Comment by rohanKanojia** [comment]
@MayankMadan97 Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff

# push changes again
git push origin yourbranchname -f
```

**Comment by MayankMadan97** [comment]
Hi @rohanKanojia,
Thanks for the warm welcome. I followed the steps as you suggested.

Glad to be here, looking to make some meaningful contributions.

**Comment by rohanKanojia** [comment]
@MayankMadan97 : I see you're contributing for the first time but the issue you picked up wasn't created for first-time contributors.

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Pull request merged**
