### PR TITLE
Organize imports

### PR DESCRIPTION
**Pull request by nishantraut**
Signed-off-by: Nishant Raut <nishant30197@gmail.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by nishantraut** [comment]
Hi @manusa and @rohanKanojia Hope you are doing well. Thought of organizing imports, feel free to reject/close PR if you think its not a good idea. Thank you :)

**Comment by rohanKanojia** [comment]
Hi, I think you should have created an issue/discussion before creating PR. In past, we agreed to use Eclipse Codeformatter[0]. Are your changes in line with eclipse import order we currently have in the project[1] ?

[0] https://www.eclipse.org/jkube/contributing/#ide-config-and-code-style
[1] https://github.com/eclipse/jkube/blob/master/ide-config/eclipse.importorder

**Comment by nishantraut** [comment]
Hi @rohanKanojia Sorry for not creating issue first, I can create one if you think we should take this forward. Yes changes are aligned with project specific settings. I can also break the PR if needed. Thanks.

**Comment by rohanKanojia** [comment]
>  I can create one if you think we should take this forward

I'm more or less okay with this change if it's aligned with the current eclipse import order. But I would check with @manusa first since he is leading the project.

There seem to be some build failures, if we want to go ahead with this we need to address these as well:
```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jkube-kit-spring-boot: Compilation failure: Compilation failure: 
[ERROR] /home/circleci/project/jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java:[65,42] package Configs does not exist
[ERROR] /home/circleci/project/jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java:[64,6] cannot find symbol
[ERROR]   symbol:   class AllArgsConstructor
[ERROR]   location: class org.eclipse.jkube.springboot.generator.SpringBootGenerator
[ERROR] -> [Help 1
```

**Comment by nishantraut** [comment]
i was having maven enforcer plugin issues while doing build on parent module, i will check. Thanks for pointing.

**Comment by manusa** [comment]
Hi @nishantraut,

Please make sure you fully read the [Contribution Guidelines](https://www.eclipse.org/jkube/contributing) for the project.
The code style is not referenced here, but we do have [Eclipse IDE configuration](https://github.com/eclipse/jkube/tree/master/ide-config) files to enforce it and a [section](https://www.eclipse.org/jkube/contributing#ide-config-and-code-style) explaining how to configure in some IDEs. There's a specific file for [import](https://github.com/eclipse/jkube/blob/dacdb74de1a0d077f0508444336af5695438d7e4/ide-config/eclipse.importorder) sorting.

These sort of global reformat commits are not what we are looking for since we'll lose quick access to git history and blame information, making it a little bit harder to tackle bugs and analysis. Please, don't spend your efforts on this.

We do follow the [boy scout rule](https://www.oreilly.com/library/view/97-things-every/9780596809515/ch08.html), so whenever you are contributing something else, some housekeeping is welcome if it is involved with the issue at hand.

**Comment by nishantraut** [comment]
Hi @manusa, Thanks for the feedback.

**Pull request closed without merging**
