### PR TITLE
feat: Webapp-Wildfly supports S2I source builds too

### PR DESCRIPTION
**Pull request by manusa**
3 build modes:
 - Docker (Kubernetes) `mvn k8s:build`
 - OpenShift-Docker (S2I Binary) `mvn oc:build -Djkube.build.strategy=docker`
 - OpenShift-S2I (S2I Source) `mvn oc:build`

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Thanks a lot for this :+1: . I thought it's going to be more involved. I would test and take a look at this PR tomorrow.

**Comment by manusa** [comment]
> ...I thought it's going to be more involved...

Implementation looks simple but it was quite involved.

The base S2I image needs to allow some way to be able to provide the packaged war and deploy it (instead of compiling it with the s2i builder image).

In this case, `wildfly-s2i` will copy any `.war` that's located in the `/tmp/src/deployments`. We can achieve this in a "hacky" way by setting the assembly name to `deployments`.

It's also important that both the Docker based image and the S2I image are in someway compatible so that we don't need to add too many specifics for each use case.

For this case, we've been lucky and most things will work OOTB for both (three in reality) scenarios.

I don't think this will be as easy for other S2I images, I'm still investigating this (which is what takes longer).

**Comment by rohanKanojia** [comment]
Which project did you use to test this? I was trying on `quickstarts/maven/webapp` but somehow my application doesn't seem to be getting exposed:
Screenshot from 2020-05-14 11-31-25
 
I tried the default URL and also with `/webapp` but it is giving me 404.
When I'm doing `oc:build` (I removed `buildStrategy=docker` from XML config). I get this error:
```
~/work/repos/jkube/quickstarts/maven/webapp : $ mvn oc:build
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< org.eclipse.jkube.quickstarts.maven:webapp >-------------
[INFO] Building Eclipse JKube :: Quickstarts :: Maven :: Webapp 1.0.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- openshift-maven-plugin:1.0.0-SNAPSHOT:build (default-cli) @ webapp ---
[INFO] oc: Using OpenShift build with strategy S2I
[INFO] oc: Running in OpenShift mode
[INFO] oc: Running generator webapp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.447 s
[INFO] Finished at: 2020-05-14T11:30:47+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jkube:openshift-maven-plugin:1.0.0-SNAPSHOT:build (default-cli) on project webapp: Execution default-cli of goal org.eclipse.jkube:openshift-maven-plugin:1.0.0-SNAPSHOT:build failed: S2I not yet supported for the webapp-generator. Use -Djkube.mode=kubernetes or -Djkube.build.strategy=docker for OpenShift mode. Please refer to the reference manual at https://www.eclipse.org/jkube/docs for details about build modes. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```

**Comment by manusa** [comment]
> Which project did you use to test this? I was trying on `quickstarts/maven/webapp` but somehow my application doesn't seem to be getting exposed..

`webapp-wildfly`, the one with the modified pom.xml in this commit that removes any sort of configuration to build images.

**Comment by manusa** [comment]
It's good because you just tested that there is no regression in the WebAppGenerator.

**Comment by rohanKanojia** [comment]
okay, it seems to be working for `webapp-wildfly`

**Pull request merged**
