### PR TITLE
Feature 1958: Add Apache Tomee sample project

### LINKED ISSUE #1958: Add Apache Tomee sample project
### Component

Kubernetes Maven Plugin

### Is your enhancement related to a problem? Please describe

Apache Tomee is very suitable to be used with JKube, but doesn't have a sample project

### Describe the solution you'd like

Sample project to show a 'skeleton' of how to create a Tomee deployment

### Describe alternatives you've considered

_No response_

### Additional context

I'll provide a PR

### PR DESCRIPTION
**Pull request by semanticfire**
## Description
Add Apache Tomee sample to QuickStarts
Fixes #1958 

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by sunix** [comment]
Hi @semanticfire 
I can see there are `deployment.yaml`, `service.yaml` and `ingress.yaml`
Can't jkube generate theses resource without the user to include them?

**Comment by rohanKanojia** [comment]
I tested this and it seems to be running okay (after changes to my push registry and pull secrets)

I found `docker.host` property a bit confusing. Shall we change this to `docker.registry` or `image.registry` instead? Maybe add a property for image user too? (since most container registries follow ${registryName}/${user}/${imageName}:${tag} approach)

We should also add a note in README.md to add pullsecrets if image is pushed to private registries (I tried with quay.io)

**Comment by semanticfire** [comment]
Please make modifications as you see fit, I've transferred what we use internally into this repo for others to use.

**Review by manusa — APPROVED** [review]

**Pull request merged**
