### PR TITLE
fixing #711 : Remove quotes from helm chart values

### PR DESCRIPTION
**Pull request by dloiacono**
Signed-off-by: dloiacono <dloiacono@gmail.com>

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
If I try linting the generated chart:
```
[ERROR] templates/: parse error at (helm-and-fragments/templates/helm-and-fragments-deployment.yaml:52): "512M"
```

Are we sure that a quoteless expression (`{{ .Values.limits_memory | default 512Mi }}`) is valid?

**Comment by manusa** [comment]
Hi @dloiacono,

After the recent changes available in 1.6.0, I think that the changes in this PR are no longer necessary.

Can we close it? do you need anything else to be covered?

**Comment by dloiacono** [comment]
> Hi @dloiacono,
> 
> After the recent changes available in 1.6.0, I think that the changes in this PR are no longer necessary.
> 
> Can we close it? do you need anything else to be covered?

HI @manusa I agree, no sense anymore. 
You can close it.

**Pull request closed without merging**
