### PR TITLE
Corrected code smell in AbstractNativeClientBuilder

### PR DESCRIPTION
**Pull request by gabriellaabdennabi**
## Description
Fix: #783 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Hello, why are these files added?

` kubernetes-maven-plugin/doc/.sample-demo.gif.icloud`
`quickstarts/maven/hello-world/src/main/java/org/eclipse/jkube/sample/helloworld/App.class `

**Comment by gabriellaabdennabi** [comment]
Hi that happened by accident when I was installing dependencies to test, I can revert the changes and just push the changed file.

**Comment by manusa** [comment]
> Hi that happened by accident when I was installing dependencies to test, I can revert the changes and just push the changed file?

Yes please, amend this commit and add only the changed file.

In order to contribute to Eclipse, you also need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Comment by manusa** [comment]
Hi @gabriellaabdennabi 
It appears you created an [Eclipse Account](https://accounts.eclipse.org/users/gabde002), but you still need to sign the ECA, please do it so we can merge your PR.
image

**Comment by gabriellaabdennabi** [comment]
Hi,
Yes I went ahead and signed it, eclipse had some issues last week with user creation and I could not sign in because of that but they fixed it.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
