### PR TITLE
feat: change Istio quickstarter to use Fabric8 Istio client

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/eclipse/jkube/issues/1505

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @rohanKanojia

**Comment by rohanKanojia** [comment]
Thanks for the PR, but there is a pull request already for this https://github.com/eclipse/jkube/pull/1511

**Comment by rohanKanojia** [comment]
I'm sorry for not updating the pull request earlier. Really sorry for wasting your time.

**Comment by Sgitario** [comment]
> I'm sorry for not updating the pull request earlier. Really sorry for wasting your time.

No problem! :D

**Comment by manusa** [comment]
Hi @Sgitario 
I'm really sorry for this. Non-committer users should comment on the issue before starting any work so that we can assign it accordingly, else we face situations like this one, where more than one user is working on the same issue simultaneously.

Thanks anyway, we do appreciate your effort anyway.

**Comment by MMajd** [comment]
@manusa @rohanKanojia @Sgitario 
I'm really sorry for the inconvenience and for not asking to be assignee before committing my PR, won't be happening again :pray:

**Pull request closed without merging**
