### PR TITLE
Fix for try with resources issue #878

### PR DESCRIPTION
**Pull request by praneethjreddy**
## Description

This change addresses Issue #878. Changed try block to try-with-resources. Also replaced anonymous implementation with lambda

[Issue](https://github.com/eclipse/jkube/issues/878)

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,
 
In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca).
 
Once you've created an eclipse account you need to update your commit message with a `Signed-off-by:` footer.

**Comment by manusa** [comment]
Hi @praneethjreddy 
Please check the [Sonar report comment](https://github.com/eclipse/jkube/pull/879#issuecomment-911964159). After your lambda removals, there is one import that is no longer needed.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
