### PR TITLE
Use static JsonMappingException #1090

### PR DESCRIPTION
**Pull request by anirudhbagri**
#1090

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
This issue was meant only for first-time contributors who are new to open source/JKube in general. You've created PRs for:

https://github.com/eclipse/jkube/issues/1090
https://github.com/eclipse/jkube/issues/1095
https://github.com/eclipse/jkube/issues/1089
https://github.com/eclipse/jkube/issues/1092


We can only accept one out of these.

**Comment by anirudhbagri** [comment]
Sure. Not a problem.

**Comment by rohanKanojia** [comment]
@anirudhbagri : Thanks. Which one should we consider for review? Also you also need to update your commit message with `Signed Off By` footer so that ECA check can pass.

**Comment by anirudhbagri** [comment]
I am picking up this one: #1095

**Pull request closed without merging**
