### PR TITLE
update runservice.java

### LINKED ISSUE #734: RunService.java: Use isEmpty() to check whether the collection is empty or not.
### Description

The following statement is reported as a code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AXCb0UvMych7Ocxsbwgc&resolved=false&types=CODE_SMELL):

https://github.com/eclipse/jkube/blob/8ca3f342372128fe12ea1572db1e37d033406a94/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RunService.java#L411

Replace with `.isEmpty`:
```java
return !ret.isEmpty() ? ret : null;
```

### Bonus

Create a unit test to verify your changes (intermediate).

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by Jayita10**
## Description
Issue Fix #734

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
You would need to create an Eclipse Account and Sign Eclipse Contributor Agreement in order for ECA check to pass. 

https://www.eclipse.org/jkube/contributing#legal

**Comment by Jayita10** [comment]
@rohanKanojia I have create an account mistakenly with an another email(not the gitHub one), so I faced conflict. Can you please guide how to resolve this?

**Comment by rohanKanojia** [comment]
I think adding a `Signed-off-by: YourName <youreclipseemail>` footer should fix it. You just need to do `git commit --amend` and then add this line at the end of commit message.

**Comment by Jayita10** [comment]
Hi @rohanKanojia, there are one more check need to pass, what to do for this?

**Comment by rohanKanojia** [comment]
Codecov check is just complaining for test coverage. I think we can skip this one

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx for your contribution!

**Pull request merged**
