### PR TITLE
Quickstarts : Upgrade Spring Boot quickstarts to latest versions (v2.7.7) #1982

### LINKED ISSUE #1982: Quickstarts : Upgrade Spring Boot quickstarts to latest versions (v2.7.7)
### Component

None

### Description

Our Spring Boot quickstarts are using more than an year-old versions of Spring Boot. These should be updated to latest 2.7.x release of SpringBoot.

Spring Boot 3.x seems to require JDK17 so we should skip it for now.

### Expected Behavior
Update Spring Boot versions of these quickstarts:
- [quickstarts/maven/spring-boot-crd](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/spring-boot-crd/pom.xml)
- [quickstarts/maven/spring-boot-camel-complete](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/spring-boot-camel-complete/pom.xml)
- [quickstarts/maven/spring-boot-crd](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/spring-boot-crd/pom.xml)
- [quickstarts/maven/spring-boot-helm](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/spring-boot-helm/pom.xml)
- [quickstarts/maven/spring-boot-watch](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/spring-boot-watch/pom.xml)
- [quickstarts/maven/spring-boot-with-jib](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/spring-boot-with-jib/pom.xml#L30)
- [quickstarts/maven/spring-boot](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/spring-boot/pom.xml#L24)
- [quickstarts/maven/spring-boot-crd](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/spring-boot-crd/pom.xml)
- [quickstarts/gradle/spring-boot-camel-complete](https://github.com/eclipse/jkube/blob/master/quickstarts/gradle/spring-boot-camel-complete/build.gradle#L2)
- [quickstarts/gradle/spring-boot-crd](https://github.com/eclipse/jkube/blob/master/quickstarts/gradle/spring-boot-crd/build.gradle#L2)
- [quickstarts/gradle/spring-boot-helm](https://github.com/eclipse/jkube/blob/master/quickstarts/gradle/spring-boot-helm/build.gradle#L2)
- [quickstarts/gradle/spring-boot-watch](https://github.com/eclipse/jkube/blob/master/quickstarts/gradle/spring-boot-watch/build.gradle#L2)
- [quickstarts/gradle/spring-boot](https://github.com/eclipse/jkube/blob/master/quickstarts/gradle/spring-boot/build.gradle#L4)

### Acceptance Criteria
- [ ] All quickstarts should be updated to latest compatible version of Spring Boot
- [ ] All quickstarts should be tested on Kubernetes/OpenShift cluster to verify if they're working okay after upgrade. You can follow the README of these quickstarts to know about their purpose.

### PR DESCRIPTION
**Pull request by Prathamkrishna**
## Description

Fixes #1982 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by Prathamkrishna** [comment]
@rohanKanojia I've agreed to the necessary legal agreements by logging in, can we run this process again?

**Comment by rohanKanojia** [comment]
strange, usually this problem is faced by first time contributors. Are you sure you've signed off your commits like you did before?

 You need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Comment by Prathamkrishna** [comment]
I had signed my pushes afaik, lemme check

**Comment by rohanKanojia** [comment]
@Prathamkrishna : Could you please compare it with your previous PR https://github.com/eclipse/jkube/pull/1408 ? Maybe check what's difference in commit signatures?

**Comment by Prathamkrishna** [comment]
I rechecked and it was sourcing from prathamkrishna@Macbook.local. I pushed from my GitHub details and logged into Eclipse and revalidated this host

**Comment by manusa** [comment]
There are 15 commits in this PR, so probably you addressed the issue for some of them but not for all.
Please squash them all into a single commit and then force push your branch.

**Comment by rohanKanojia** [comment]
@Prathamkrishna : polite ping, are you still working on this?

**Comment by Prathamkrishna** [comment]
hey, hi. last i worked on this, i changed the versions of spring boot projects and had pushed the changes in the above commits.

**Comment by rohanKanojia** [comment]
Marc seems to have requested squashing your changes. I also see ECA check failing, it's required in order to merge this PR. Could you please look into these whenever you get time?

**Pull request closed without merging**
