### PR TITLE
doc: #90 Updated module overview diagram to current status

### PR DESCRIPTION
**Pull request by manusa**
Closes: #90 
module_overview

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Could you please update README image link too?

**Comment by manusa** [comment]
> Could you please update README image link too?

I don't think this model replaces the one on the readme. The intention of this one is to show current status. Which differs  a lot from what the one in the readme shows.

We should work with this one to establish next steps in the project (especially profiles).

**Comment by rohanKanojia** [comment]
For showing current status, it needs to be somewhere. Maybe inside jkube-kit's README. I'm not sure if someone interested in project would look into target folders for the diagram

**Comment by manusa** [comment]
I think what you mention belongs more to 
https://github.com/eclipse/jkube/tree/master/jkube-kit/doc (current root folder)

Or even some kind of formal Roadmap (which we don't yet have).

I would rather create a new issue to update/refactor current JKube Kit docs or to create a Roadmap, and maybe also embed them in the website (just like the maven plugins). But wouldn't do it in scope of this one.

I initially created the diagram to design a **phased** decoupling from Maven (which we didn't do in the end as it was performed in a single run).

I think this diagram is still important (that's why it's being maintained) because we can compare it to Roland's original design and see what we're missing (e.g. profiles). We can use this internally to decide on next steps and prioritize upcoming tasks.

**Comment by rohanKanojia** [comment]
Umm, okay. Let me merge this then

**Pull request merged**
