### PR TITLE
Clean up

### LINKED ISSUE #807: ClassUtilTest: Remove unused imports
### Description
The class [ClassUtilTest](https://github.com/eclipse/jkube/blob/bc812977cc26684611552681ab336bc7f1b8c58c/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/ClassUtilTest.java) contains multiple unused imports.

Locate those statements and remove them.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by vlaetansky**
## Description
Fix #807 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

#806 #807

### CODE REVIEW

**Comment by manusa** [comment]
Hi @vlaetansky 
The purpose of the extremely easy first-timers-only issues is for novice users to get acquainted with the project and the Eclipse Foundation contributing purpose. You should only choose **one** of these issues to fix.
If you like contributing to JKube, we also have help-wanted issues for users who have already contributed to the project and that want to keep doing it.

The first step to fix one of the first-timers-only is to comment on the issue you want to tackle so we can assign it to you.

Regarding this PR, you did fix some of the issues, but missed the important part which is to commit your changes using an account that signed the Eclipse Contributor Agreement.

**Comment by vlaetansky** [comment]
I have pulled the master branch into my repository's master branch, but i am not sure if it is what i was supposed to do. Please tell me if i should force push it back to my commit or leave it as it is right now.

**Comment by rohanKanojia** [comment]
@vlaetansky : LGTM :+1: , Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
ECA check is green now :-)

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
