### PR TITLE
Issue fix #2810 chore: updated to latest quarkus version 

### LINKED ISSUE #2810: Update `quickstarts/maven/quarkus` to latest version
### Component

None

### Description

Our quickstarts/maven/quarkus is using a slightly old version of Quarkus. It should be updated to the latest version (`3.8.2` at the time of writing)

https://github.com/eclipse/jkube/blob/c4ee9d4e9432297c50d9385a8c06d1fea0f75e3a/quickstarts/maven/quarkus/pom.xml#L35

After changing the version, you might face problems regarding missing imports. They just need to be moved to `jakarta` package instead:
- `javax.ws.rs.GET` -> `jakarta.ws.rs.GET`
- `javax.inject.Singleton` -> `jakarta.inject.Singleton`

:warning: A Kubernetes Cluster is required to test that JKube's Kubernetes Maven Plugin can deploy application to Kubernetes cluster

### Expected Behavior
Quarkus quickstart is updated to latest version

### Acceptance Criteria
- [ ] Quarkus quickstart builds successfully after version bump
- [ ] Quickstart is tested on a Kubernetes cluster to verify it's working as documented in README.md

### PR DESCRIPTION
**Pull request by l3002**
## Description

Fixes #2810

Updated `Quarkus` to version `3.9.1` and fixed all the breaking imports.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2864 (_2024-04-01T05:15:56Z_)

:gear: [JKube E2E Tests (8504170013)](https://github.com/jkubeio/ci/actions/runs/8504170013) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2864)](https://github.com/jkubeio/ci/actions/runs/8504170013/job/23290705865)

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@l3002 : Did you test the quickstart on minikube and OpenShift?

**Comment by l3002** [comment]
> @l3002 : Did you test the quickstart on minikube and OpenShift?

I had tested it using `minikube` and the image build and resources build seems to be working fine, I'm having some trouble with the push and apply part but I'm sure that it is a local issue.

The issue with `k8s:push` might be related to the registry url or credentials and issue with `k8s:apply` seems to be with pulling the images. Though it is applying the deployment generated, the deployment seems to be stuck in `ImagePullBackOff` state.

I'm trying to figure out what the issue is. For now lets, keep the two PRs in `waiting for approval` state only.

I'll update these after resolving it on my end in 1-2 days.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
