### PR TITLE
Replaced exact with implementation specific

### PR DESCRIPTION
**Pull request by Onyinye91-ctrl**
## Description
Replaced exact with implementation specific #979

Please provide a description of what your PR does providing a link (if applicable) to the issue it fixes.
-->

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by Onyinye91-ctrl** [comment]
@manusa Sorted

**Comment by manusa** [comment]
> @manusa What change let me fix it

What I stated in the other PR: https://github.com/eclipse/jkube/pull/979#issuecomment-938356070

---

So, for the current failure, if you check the build log, you'll notice a failing test:
```
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 32, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  ingress-xml-config/pom.xml
```

Which is complaining about this:
https://github.com/eclipse/jkube/blob/21ddf9f609068339d66115925ba9843a27264e09/kubernetes-maven-plugin/it/src/it/ingress-xml-config/expected/zero-config-networkv1-host-enricher-config/kubernetes.yml#L122

Following the same reasoning for the previous test modification, you'll also need to replace this field with the new value.

**Comment by manusa** [comment]
Superseded by #999

**Pull request closed without merging**
