### PR TITLE
feat: update version of micronaut

### LINKED ISSUE #1429: [Maven Quickstarts] : Update Micronaut quickstart to v3.4.1
### Description
Our current micronaut maven quickstart seems to be outdated. It needs to be updated to latest version of micronaut.

https://github.com/eclipse/jkube/blob/ded7049e0ff253e04ebf1fddfc265bf25f1b636b/quickstarts/maven/micronaut/pom.xml#L24

- [ ] Update Micronaut version to latest release
- [ ] Verify Kubernetes Maven Plugin is working with the updated version by deploying an application to [minikube](https://minikube.sigs.k8s.io/docs/)
- [ ] Verify OpenShift Maven Plugin is working with updated version by deploying the application to [Red Hat Developer Sandbox](https://developers.redhat.com/developer-sandbox/get-started)

### PR DESCRIPTION
**Pull request by Mohd-Farhan**
## Description

Fixes #1429 

Signed-off-by: Mohd-Farhan <mohammadfarhan3255@gmail.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by Mohd-Farhan** [comment]
I try to run it on minikube but there is some port issue that's why I did not verify maven kubernetes plugin.

**Comment by rohanKanojia** [comment]
@Mohd-Farhan : Have you created an Eclipse Account and signed off ECA? You need to add `Signed-off by: ` footer in your commit message.

**Comment by rohanKanojia** [comment]
Strange, not sure why ECA check is failing. 

Could you please check my blogpost for step by step guide towards contributing to Eclipse JKube and see if you've followed steps correctly?

https://rohaan.medium.com/how-to-contribute-to-eclipse-jkube-f3bc7f902bf4

**Comment by rohanKanojia** [comment]
@Mohd-Farhan : ECA check seems to be failing again. Do you remember which email you used to create Eclipse Account?

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Pull request merged**
