### PR TITLE
fix(oc-build): Correctly pass Docker build-arg from the build configuration to the Openshift build strategy

### LINKED ISSUE #2860: Build args not applied as ARG (external dockerfile openshift-maven)
### Describe the bug

I am trying to specify the image version from the pom which I can then use in an ARG in my dockerfile when building on openshift. ([related docs](https://eclipse.dev/jkube/docs/openshift-maven-plugin/#_build_args)) 

### Eclipse JKube version

1.16.2

### Component

Kubernetes Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

1. Configure a build arg like so: [pom.xml.txt](https://github.com/eclipse/jkube/files/14789702/pom.xml.txt)
```xml
<plugin>
	<groupId>org.eclipse.jkube</groupId>
	<artifactId>openshift-maven-plugin</artifactId>
	<version>1.16.2</version>
	<executions>
		<execution>
			<id>build-main-container</id>
			<phase>package</phase>
			<goals>
				<goal>build</goal>
			</goals>
			<configuration>
				<buildStrategy>docker</buildStrategy>
				<images>
					<image>
						<name>${openshift.registry}/helloworld:%l</name>
						<build>
							<contextDir>${project.basedir}/src/main/docker/</contextDir>
							<dockerFile>Dockerfile</dockerFile>
							<args>
								<IMAGEVERSION>latest</IMAGEVERSION>
							</args>
						</build>
					</image>
				</images>
			</configuration>
		</execution>
	</executions>
</plugin>
```
2. Specify the dockerfile under src/main/docker as follows:
```
ARG IMAGEVERSION
FROM docker.io/alpine:${IMAGEVERSION} as builder

RUN touch test.txt

FROM docker.io/alpine:${IMAGEVERSION}
COPY --from=builder test.txt test.txt

ENTRYPOINT ["ls"]
```

3. run `mvn clean verify -Dopenshift.namespace=yournamespacehere`

### Expected behavior

I expect the build arg to be applied and the ARG in the Dockerfile to be filled at build time.

### Runtime

OpenShift

### Kubernetes API Server version

1.25.3

### Environment

Linux, other (please specify in additional context)

### Eclipse JKube Logs

```shell
[INFO] --- oc:1.16.2:build (build-main-container) @ test ---
[INFO] oc: Using OpenShift build with strategy Docker
[INFO] oc: Using Dockerfile: /home/roelof/Documents/code/frb-common/helloworld/src/main/docker/Dockerfile
[INFO] oc: Using Docker Context Directory: /home/roelof/Documents/code/frb-common/helloworld/src/main/docker
[WARNING] oc: Dockerfile /home/roelof/Documents/code/frb-common/helloworld/src/main/docker/Dockerfile does not contain an ADD or COPY directive to include assembly created at maven. Ignoring assembly.
[INFO] oc: [image-registry.openshift-image-registry.svc:5000/bl-roelofsnijder/helloworld:latest]: Created docker source tar /home/roelof/Documents/code/frb-common/helloworld/target/docker/image-registry.openshift-image-registry.svc/5000/bl-roelofsnijder/helloworld/latest/tmp/docker-build.tar
[INFO] oc: Adding to Secret pullsecret-jkube
[INFO] oc: Using Secret pullsecret-jkube
[INFO] oc: Updating BuildServiceConfig helloworld-s2i for Docker strategy
[INFO] oc: Adding to ImageStream helloworld
[INFO] oc: Starting Build helloworld-s2i
[INFO] oc: Waiting for build helloworld-s2i-11 to complete...
[INFO] oc: Adding cluster TLS certificate authority to trust store
[INFO] oc: time="2024-03-28T12:48:54Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
[INFO] oc: I0328 12:48:54.750934       1 defaults.go:112] Defaulting to storage driver "overlay" with options [mountopt=metacopy=on].
[INFO] oc: Caching blobs under "/var/cache/blobs".
[INFO] oc: 
[INFO] oc: Pulling image docker.io/alpine ...
[INFO] oc: Trying to pull docker.io/library/alpine:latest...
[INFO] oc: Getting image source signatures
[INFO] oc: Copying blob sha256:4abcf20661432fb2d719aaf90656f55c287f8ca915dc1c92ec14ff61e67fbaf8
[INFO] oc: Copying config sha256:05455a08881ea9cf0e752bc48e61bbd71a34c029bb13df01e40e3e70e0d007bd
[INFO] oc: Writing manifest to image destination
[INFO] oc: Storing signatures
[INFO] oc: Adding transient rw bind mount for /run/secrets/rhsm
[INFO] oc: time="2024-03-28T12:48:57Z" level=warning msg="missing \"IMAGEVERSION\" build argument. Try adding \"--build-arg IMAGEVERSION=<VALUE>\" to the command line"
[INFO] oc: [1/2] STEP 1/3: FROM docker.io/alpine: AS builder
```

### Sample Reproducer Project

_No response_

### Additional context

Ran on Openshift 4 [generatedbuildconfig.yaml.txt](https://github.com/eclipse/jkube/files/14789762/generatedbuildconfig.yaml.txt) The build config exported from openshift. Notice the args are available as ENV.
https://github.com/eclipse/jkube/pull/1395 seems related.

### PR DESCRIPTION
**Pull request by sunix**
## Description

Fixes #2860

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2895 (_2024-04-11T09:52:52Z_)

:gear: [JKube E2E Tests (8644832571)](https://github.com/jkubeio/ci/actions/runs/8644832571) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2895)](https://github.com/jkubeio/ci/actions/runs/8644832571/job/23700775135)

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
We need to make sure that build args defined as properties still work:

https://eclipse.dev/jkube/docs/openshift-maven-plugin/#property-buildargs

Could you please confirm this?

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by sunix** [comment]
> We need to make sure that build args defined as properties still work:
> 
> https://eclipse.dev/jkube/docs/openshift-maven-plugin/#property-buildargs
> 
> Could you please confirm this?

I am currently debugging, but there are some issues. I will create another issue once I can figure out what's going on. For sure there is a problem in kubernetes-maven-plugin when build args are injected to a FROM statement.

**Pull request merged**
