### PR TITLE
Make expose labels created by ExposeEnricher persistent

### PR DESCRIPTION
**Pull request by rnetuka**
~~According to docs https://www.eclipse.org/jkube/docs/openshift-maven-plugin#resource-route-generation, Openshift services should be exposed by default. Only when you add expose=false label, no routes will be generated.~~

ExposeEnricher should propagate expose: true label to RouteEnricher for services exposed by default (running on port 80 etc.) Routes should be generated for such services.

Actual behavior:
~~If no expose label is provided, the check _isExposedService(serviceMetadata)_ returns false and no route is created.~~
ExposeEnricher doesn't propagate expose: true label to RouteEnricher. The check _isExposedService(serviceMetadata)_ returns false and no route is created.

Fix proposal:
~~If no expose label is provided, add it by default to expose=true~~
Propagate expose: true label created by ExposeEnricher to RouteEnricher

Related to https://issues.redhat.com/browse/ENTESB-15988

### CODE REVIEW

**Comment by manusa** [comment]
Relates to #602

**Comment by manusa** [comment]
Please, check this comment (https://github.com/eclipse/jkube/issues/602#issuecomment-791371801) and see how it aligns with the current proposed fix.

**Comment by rnetuka** [comment]
@manusa I've checked your comment and I can confirm that ExposeEnricher works ok and adds expose: true label (since the service port is 80 -> exposed by default as you've said). 

However, **RouteEnricher** still fails. The expose: true label is not detected by _isExposedService(serviceMetadata)_ check (it returns _false_, so the route creation is skipped). Expected behavior: route is created.

<jkube.enricher.jkube-service.expose>true</jkube.enricher.jkube-service.expose> doesn't solve my problem since it addresses functionality that already works in my case. Providing _expose: true_ manually in _service.yml_ works, but I see it more like a workaround, since the route should be created by default in my case.

You can check yourself:
https://github.com/fabric8-quickstarts/spring-boot-cxf-jaxws, branch fuse-7.x.sb2.redhat
> mvn oc:deploy -Popenshift

**Comment by manusa** [comment]
Hi @rnetuka 
Routes should be automatically created for applications with services that have ports exposed in the following set (80, 443, 8080, 9080, 9090, 9443), without any additional configuration.
From your changes, apparently, we'll now be exposing services in any port, which I'm not sure is the expected behavior (docs need to be updated too).
I'll thoroughly check the provided examples and logs, because I think I may be missing something, and get back to you.

**Comment by rnetuka** [comment]
@manusa This is the problem, that routes are _not_ created in my case (fabric8-quickstarts). In **RouteService**, there is a check **isExposedService(serviceMetadata) ** and it checks for some labels in metadata. These labels are not present, so the route is not created.
https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java#L107
https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L930

**Comment by manusa** [comment]
Yes, I understand that. The question is why are those labels not in the generated Service.
If it's because it's not one of those "exposable" service ports (80, 443, 8080, 9080, 9090, 9443), or for some other reason.
Anyway, I'm starting to check now.

**Comment by rnetuka** [comment]
@manusa The services from fabric8-quickstarts should be on port 80. When I was checking, the ExposeEnricher worked fine and generated expose: true label. However, in RouteEnricher, there is a ServiceBuilder (instead of service) and that is not modified by the ExposeEnricher. I think it needs to be mofidied too. 

See the updated PR to check what I mean.

**Comment by manusa** [comment]
Checking ;)

**Comment by manusa** [comment]
There seems to be something very wrong in the ExposeEnricher, I don't think that the labels get persisted, not sure how the expose label ends up in the Services right now though.

**Comment by manusa** [comment]
I'm not really sure why the `ExposeEnricher` works right now, probably depending on the Fabric8 Kubernetes Client version things might or might not work as expected.

The fact is that `ExposeEnricher` should be using the visitor pattern instead of modifying built resources (which in reality should provide immutability to the Builder based items).

So basically what you need to do is remove the other part and keep yours:
- Move your new `TypedVisitor` to the `create` method
- Change the argument of the `enrichService` method to `ServiceBuilder`
- Make your visitor call the enrichService and refactor the logic there
  - Instead of using `editMetadata` use `editOrNewMetadata`

Also, you could use the time to make the webPorts field static (`WEB_PORTS`) ;)

If you want us to create an additional commit on top of yours with the suggested changes, just ask.

Thanks!

**Review by manusa — CHANGES_REQUESTED** [review]
Requested changes are in previous comment

**Comment by rnetuka** [comment]
Thanks for the review! I've made the changes to the PR.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
