### PR TITLE
chore (quickstarts) : Updated pom.xml in micronaut-customized-image quickstart (#2310)

### LINKED ISSUE #2310: [Quickstarts] : Replace `${parent.version}` with `${project.parent.version}` in `quickstarts/maven/micronaut-customized-image`
### Component

None

### Description

_Originally posted by @ShivangMishra in [Gitter Conversation](https://matrix.to/#/!QryyIuhARjRcebsrTd:gitter.im/$bUIitQJg3FB5lqg5DMDY_BZH5sfpMMdatt575rgNcTE?via=gitter.im&via=matrix.org)_

When running `mvn clean install` in `quickstarts/maven/micronaut-customized-image`, we get this warning:

```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eclipse.jkube.quickstarts.maven:micronaut-customized-image:jar:1.13.1
[WARNING] The expression ${parent.version} is deprecated. Please use ${project.parent.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

As suggested by maven, we should change this line : 
https://github.com/eclipse/jkube/blob/1ffc921c99a345320ce2a59e2e8bf5bcb5469277/quickstarts/maven/micronaut-customized-image/pom.xml#L45

to : 
```diff
-    <micronaut.version>${parent.version}</micronaut.version>
+    <micronaut.version>${project.parent.version}</micronaut.version>
```

### Steps to Contribute:
1. In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca).
2. Configure your Git Username  `git config --global user.name "John Doe"`
3. Configure your Git email `git config --global user.email johndoe@example.com`
4. Fork JKube repository on Github 
5. Clone JKube repository `git@github.com:eclipse/jkube.git`
6. Add git remote for jkube fork `git remote add upstream git@github.com:eclipse/jkube.git`
7. Add git remote for your fork `git remote add Your-GitHub-Username git@github.com:Your-GitHub-Username/jkube.git`
8. Create new branch for this task `git checkout -b pr/issue[issueNumber]`
9. Update line number 45 in `quickstarts/maven/micronaut-customized-image/pom.xml` to `<micronaut.version>${project.parent.version}</micronaut.version>`
10. Add your changes to git index `git add quickstarts/maven/micronaut-customized-image/pom.xml`
15. Commit your changes `git commit --signoff -m "chore (quickstarts) : Updated pom.xml in micronaut-customized-image quickstart (#issuenumber)"`
16. Push your changes to your fork `git push Your-Github-Username  pr/issue[issueNumber]`
17. Create pull request from GitHub interface

### Expected Behavior
No warning should appear while building this quickstart

### Acceptance Criteria
- Property should be updated to `project.parent.version` in `quickstarts/maven/micronaut-customized-image/pom.xml`

### PR DESCRIPTION
**Pull request by ShantKhatri**
## Description

When running mvn clean install in quickstarts/maven/micronaut-customized-image, we get this warning for  ${parent.version}, now after updating it to  ${project.parent.version} and no warning comes.

Fixes #2310 

Signed-off-by: Prashantkumar Khatri <prashantkhatri202@gmail.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@ShantKhatri : ECA check is failing. Have you created Eclipse Account and signed ECA?

**Comment by ShantKhatri** [comment]
> @ShantKhatri : ECA check is failing. Have you created Eclipse Account and signed ECA?

Yes, I have done but email are different on both that's why it's failing.

**Comment by rohanKanojia** [comment]
Could you please update commit to add signoff footer for correct email?
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff

git push origin pr/issue2310 -f
```

**Comment by ShantKhatri** [comment]
> Could you please update commit to add signoff footer for correct email?
> 
> ```
> # (Optional): Configure Git User and Email
> git config user.name "Your Name"
> git config user.email "your_email@example.com"
> 
> # Amend your previous commit with signed off footer
> git commit --amend --signoff
> 
> git push origin pr/issue2310 -f
> ```
Done but again ECA check is failing.

**Comment by rohanKanojia** [comment]
@ShantKhatri : Could you please squash your commits into one?

**Comment by ShantKhatri** [comment]
> @ShantKhatri : Could you please squash your commits into one?

Could you please merge this PR?

**Comment by manusa** [comment]
image

**Comment by ShantKhatri** [comment]
> image

Yes, this is because the email with which I registered in eclipse contributor agreement is different and I'm not able to change email in eclipse foundation account and when I changed email in github it showing the same because It's considering email with which changes were done.

**Comment by manusa** [comment]
You've committed your changes with that email account
See https://github.com/eclipse/jkube/pull/2311#issuecomment-1653393694, especially the part for `git config user.email`

No changes can be accepted unless the ECA validation passes.

**Comment by rohanKanojia** [comment]
Please update your commit with the email you used for creating Eclipse Account:
```
git commit --amend --author="John Doe <john@doe.org>" # Email should be the one you used for Eclipse
```

Then force push to this branch
```
git push origin pr/issue2310 -f
```

**Comment by ShantKhatri** [comment]
> Please update your commit with the email you used for creating Eclipse Account:
> 
> ```
> git commit --amend --author="John Doe <john@doe.org>" # Email should be the one you used for Eclipse
> ```
> 
> Then force push to this branch
> 
> ```
> git push origin pr/issue2310 -f
> ```

Thanks a lot!

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Pull request merged**
