### PR TITLE
fix #972 . Making variables final

### LINKED ISSUE #972: LogOutputSpec.java: Member variables can be declared final
### Description
`LogOutputSpec` declares several class fields that are only initialized in the constructor. They can be declared final.

The following code fragment:

https://github.com/eclipse/jkube/blob/969025bf6bd21f22ec02ef4a72174ae49aaad5bb/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogOutputSpec.java#L44-L47

- [x] should be changed to:
```java
    private final String prefix;
    private final Ansi.Color color;
    private final DateTimeFormatter timeFormatter;
    private final String file;
```
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by mihirterna**
Signed-off-by: Mihir Kulkarni <31316452+mihirterna@users.noreply.github.com>

## Description
fix for issue #972. Making variables final.

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,
 
In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca).
 
Once you've created an eclipse account you need to update your commit message with a `Signed-off-by:` footer.
 
You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"
 
# Amend your previous commit with signed off footer
git commit --amend --signoff
```

Kind reminder, it's really important that when you contribute to an Open Source repo, you read first the [contributing guidelines](https://www.eclipse.org/jkube/contributing).

**Comment by manusa** [comment]
This will still fail since you now have 3 commits with different authors. You should have done what I suggested in my comment.

You now need to squash your commits into a single one that's signed by the valid user.

**Comment by mihirterna** [comment]
Let me close this PR, and create a new one.

**Pull request closed without merging**
