### PR TITLE
Fixed SonarCloud vulnerability by making DEFAULT_PREFIX field private and final

### PR DESCRIPTION
**Pull request by param-thakker**
## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x ] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@param-thakker : Thanks for your PR. You would need to create an Eclipse Account and sign Eclipse contributor Agreement in order to contribute https://www.eclipse.org/jkube/contributing#legal

**Comment by param-thakker** [comment]
> @param-thakker : Thanks for your PR. You would need to create an Eclipse Account and sign Eclipse contributor Agreement in order to contribute https://www.eclipse.org/jkube/contributing#legal

I just finished doing that! Let me know if I need to do anything else.

**Comment by manusa** [comment]
image

**Comment by param-thakker** [comment]
@manusa Do I have to do anything else for this PR to merge? As I said, I have already created an Eclipse Account and also signed the Eclipse contributor Agreement. Please let me know.

**Comment by manusa** [comment]
Hi @param-thakker 
I'm sorry, my message was a little bit unclear.
image

You need to set the author of the commit to whatever email account you used to [create](https://github.com/eclipse/jkube/pull/742#issuecomment-870287130) the Eclipse Account and sign the ECA.

You also need to sign-off your commit with that account.

You can do this by executing the following command in your current branch and replacing the email with the appropriate one :
```shell
git -c "user.email=email-that-signed-eca@example.com" commit --amend -s --reset-author
```
Then force push your branch to send the changes to your origin remote repository.

**Comment by param-thakker** [comment]
@manusa I just committed again with the changes you mentioned. Please let me know if it's ok! Thank you for your help.

**Comment by manusa** [comment]
Hi @param-thakker 

> Please let me know if it's ok! Thank you for your help.

I don't think you ran the specific command I proposed. Now we have 3 commits, and only the second has the right metadata.

**Comment by manusa** [comment]
You need to squash your changes into a single commit and set the author and sign-off as suggestes, else the eclipsefdn/eca check won't pass.

**Pull request closed without merging**
