### PR TITLE
(jkube-kit/jkube-kit-vertx/) : Migrate tests from JMockit to Mockito

### PR DESCRIPTION
**Pull request by baruKreddy**
Signed-off-by: baruKreddy [bhargavirkotha@gmail.com](mailto:bhargavirkotha@gmail.com)

Fixes https://github.com/eclipse/jkube/issues/1601

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
Mergin, but note that the assertions have not been refactored to use AssertJ

**Comment by manusa** [comment]
> @baruKreddy : Could you please create a follow up PR to refactor assertions?

Anurag still has to do the JUnit migration, I think he can take care of that.

But just note that the AC of the issue should be checked for each PR.

**Comment by rohanKanojia** [comment]
okay, I will take care from next time

**Comment by manusa** [comment]
> okay, I will take care from next time

???

**Comment by rohanKanojia** [comment]
> ???

I will try not to miss this in reviews from next time

**Comment by manusa** [comment]
Well, the comment is more intended for contributors. We should check that the AC is complete during our review process, but this **must** be done and double checked by the person contributing.

**Comment by baruKreddy** [comment]
@manusa well I thought I can make up a follow up PR for assertions separately and didn't thought of all this. Sorry for the chaos/confusion @rohanKanojia .

**Pull request merged**
