### PR TITLE
RamananR : FIX #784 :  Replacing hamcrest with AssertJ

### LINKED ISSUE #784: EnvUtilTest.java: Replace hamcrest with AssertJ
### Description
We are replacing the usage of Hamcrest assertions with AssertJ all over the project.

In [EnvUtilTest.java](https://github.com/eclipse/jkube/blob/813074705147f9423dd807385c0d40e4670ddf9a/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java), replace any usage of Hamcrest with the AssertJ (`org.assertj.core.api.Assertions.assertThat`).

e.g. 
https://github.com/eclipse/jkube/blob/813074705147f9423dd807385c0d40e4670ddf9a/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java#L401

should be changed to:
```java
        assertThat(timestamp).isEqualTo(new Date(1445385600000L));
```

### Bonus
Replace the rest of assertions (`org.junit.Assert.*`) with AssertJ too.

### PR DESCRIPTION
**Pull request by ramananrpn**
## Description
Fix #784 
Replacing hamcrest with AssertJ

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by ramananrpn** [comment]
retest this please

**Comment by ramananrpn** [comment]
#784 @manusa Please Review this

**Comment by ramananrpn** [comment]
#784 @rohanKanojia Please review this

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
