### PR TITLE
Update AssemblyFiles.java

### LINKED ISSUE #1782: [Hacktoberfest] AssemblyFiles.entries may be 'final'
### Description
The following statement is reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/892ba7092627a7f0712ff68427361fb2d9cd976d/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyFiles.java#L32
 
- [x] should be changed to:
```java
    private final List<AssemblyFileEntry> entries = new ArrayList<>();
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by manish-singh-bisht**
Fix #1782 
solved: AssemblyFiles.entries may be 'final' #1782

### CODE REVIEW

**Comment by manish-singh-bisht** [comment]
Hey @manusa ,I say your Github,ton of contribution, visited your website https://www.marcnuri.com (amazing) .I am also interested in contributing big to big projects like you did in the field of kubernetes etc, I too want to be a part of communities like CNCF,Linux Foundation etc. Can you please help me with some guidance .This is my first Hacktoberfest , I started coding 3 months ago in July and I know basic java and all the dsa part till dynamic programming . Can you please guide me on what to do next, should I learn some java libraries,should i jump into web dev etc ,please guide me. I will be thankful to you. I know its not the platform to talk all this but I badly need some guidance from some mentor in open source.
Thank you.

**Comment by anurag-rajawat** [comment]
Hi @manish-singh-bisht 
Thanks a lot for contributing to Eclipse JKube 👍

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a Signed-off-by: footer. You can do it like this:

Amend your previous commit with signed off footer
```shell
git commit --amend --signoff
```

**Comment by manish-singh-bisht** [comment]
Hey @anurag-rajawat  is there anything else to be done? Thank you

**Comment by anurag-rajawat** [comment]
> Hey @anurag-rajawat is there anything else to be done?

Be patient, we will review your PR soon.

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
> Hey @manusa ,I say your Github,ton of contribution, visited your website https://www.marcnuri.com (amazing) .I am also interested in contributing big to big projects like you did in the field of kubernetes etc, I too want to be a part of communities like CNCF,Linux Foundation etc. Can you please help me with some guidance .This is my first Hacktoberfest , I started coding 3 months ago in July and I know basic java and all the dsa part till dynamic programming . Can you please guide me on what to do next, should I learn some java libraries,should i jump into web dev etc ,please guide me. I will be thankful to you. I know its not the platform to talk all this but I badly need some guidance from some mentor in open source. You can point me to resources as well as you must be busy. Thank you.


Hi @manish-singh-bisht,

Thx for you kind words.
I usually like to remind people that they shouldn't compare their GitHub profile (or similar metrics) to someone else's, especially to someone who works professionally on open source (like myself).
If you're truly interested in open source and in free software in general (it's also fine if you are doing this because you're seeking a job or wish to progress in your career, but then you might want advice from someone else, I'm no expert in that matter), I'd advise you to involve in a project in which you depend on, on a daily basis. Contributing is not only about code, but is also about being involved in the community, answering questions, documenting, promoting, and so on. Just pick that project, see if the community around that project is welcoming, and try to get involved.

**Comment by manish-singh-bisht** [comment]
Thank you @manusa for your advice, I asked another open source contributer and that person too said "Open source is more about community",
Thank you, I will find a community and work with them.
Have a nice day ahead.

**Pull request merged**
