### PR TITLE
Image name should be able to handle image names when both tag and digest are provided

### LINKED ISSUE #2545: ImageName should be able to handle Image names when both tag and digest are provided
### Component

None

### Description

As described in this comment in [ORAS](https://github.com/oras-project/oras-go) [registry/reference.go](https://github.com/oras-project/oras-go/blob/3b1dd0e9700082fe7bc690a745263c06361417dd/registry/reference_test.go):

><--- path --------------------------------------------> |  - Decode `path`
<=== REPOSITORY ===> <--- reference ------------------> |    - Decode `reference`
<=== REPOSITORY ===> @ <=================== digest ===> |      - Valid Form A
<=== REPOSITORY ===> : <!!! TAG !!!> @ <=== digest ===> |      - Valid Form B (tag is dropped)
<=== REPOSITORY ===> : <=== TAG ======================> |      - Valid Form C
<=== REPOSITORY ======================================> |    - Valid Form D

When both tag and digest are provided, the tag should be ignored and digest should be used. Currently, ImageName is not able to handle this scenario and throws an exception.

### Expected Behavior
ImageName should be able to handle ImageName with both tag and digest (e.g.  `registry.example.com/hello-world:@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9`) provided and give precedence to digest.

### Acceptance Criteria
- [ ] ImageName is updated to handle scenarios including both tag and digest

### PR DESCRIPTION
**Pull request by Devashishbasu**
Added code to handle image names when both tag and digest are provided

Fixes #2545 

## Type of change

 - [ X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2615 (_2024-02-03T14:31:08Z_)

:gear: [JKube E2E Tests (7767538818)](https://github.com/jkubeio/ci/actions/runs/7767538818) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2615)](https://github.com/jkubeio/ci/actions/runs/7767538818/job/21184465990)

**Comment by Devashishbasu** [comment]
Hii @rohanKanojia when i am uncommenting this test  

//"registry.example.com/hello-world:@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9",   

it is giving error as

java.lang.IllegalArgumentException: Given Docker name 'registry.example.com/hello-world:@sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9' is invalid:
   * image part 'hello-world:' doesn't match allowed pattern '[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?'
See http://bit.ly/docker_image_fmt for more details

but when i am removing the ":" in "hello-world:@sha256" then this test case passes....i think this test case is not aligning with NAME_COMPONENT_REGEXP = "[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?";

**Comment by rohanKanojia** [comment]
@Devashishbasu : hello, what is status of this pull request? Is this duplicate of https://github.com/eclipse/jkube/pull/2625 ?

**Comment by Devashishbasu** [comment]
> @Devashishbasu : hello, what is status of this pull request? Is this duplicate of #2694 ?

i have kept it open for my reference  i will close it as soon as i m done with the issue

**Pull request closed without merging**
