### PR TITLE
Removed declared exception in ResourceMojo.extractEnricherConfig 

### LINKED ISSUE #2780: ResourceMojo.extractEnricherConfig The declared Exception exception is never thrown
### Description

The method [ResourceMojo.extractEnricherConfig](https://github.com/eclipse/jkube/blob/6818c5bdf610203171cf9536753565b56cb19434/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java#L252) declares an Exception that is never thrown.

The following line
https://github.com/eclipse/jkube/blob/6818c5bdf610203171cf9536753565b56cb19434/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java#L252

- [ ] should be changed to:

```java
    private ProcessorConfig extractEnricherConfig() {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by waynemorphic**
## Description

Fixes #2780

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2786 (_2024-03-07T17:02:28Z_)

:gear: [JKube E2E Tests (8191971018)](https://github.com/jkubeio/ci/actions/runs/8191971018) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2786)](https://github.com/jkubeio/ci/actions/runs/8191971018/job/22402424099)

**Comment by rohanKanojia** [comment]
@waynemorphic : ECA check is failing, Did you create Eclipse Account and sign ECA?

**Comment by waynemorphic** [comment]
> @waynemorphic : ECA check is failing, Did you create Eclipse Account and sign ECA?

I have just created an Eclipse Account but with a different email address from the one I have used to Sign-off-by. Will that be an issue?

**Comment by waynemorphic** [comment]
> > @waynemorphic : ECA check is failing, Did you create Eclipse Account and sign ECA?
> 
> I have just created an Eclipse Account but with a different email address from the one I have used to Sign-off-by. Will that be an issue?

Validated ✅

**Review by rohanKanojia — APPROVED** [review]

**Comment by waynemorphic** [comment]
@rohanKanojia , can I pick another `first-timers-only` issue when this PR is approved and merged?

**Comment by rohanKanojia** [comment]
@waynemorphic :[`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [`good first issue` / `help wanted` labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22) . Or maybe create some new issue if you find something that should be fixed.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
