### PR TITLE
Quickstart: using Jitpack as plugin repository

### LINKED ISSUE #732: Quickstart using Jitpack as plugin repository
### Description

Testing the newly implemented features of Eclipse JKube prior to a release is critical to deliver a great product.

For users reporting bugs, it might be helpful to validate that an issue was effectively fixed by being able to use the latest SNAPSHOT from the main/master branch.

Since we don't provide nightly builds (Jitpack seems like a much more powerful option), we need to provide better instructions to use Jitpack instead.

### What to do

Provide a Maven quickstart that uses Jitpack as repository and pluginRepository using the [quickstarts/maven/zero-config](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/zero-config) as reference.

Changes:
| | Change |
| - | - |
| location | quickstarts/maven/zero-config-jitpack |
| artifactId | jkube-maven-sample-zero-config-jitpack |
| name |  Eclipse JKube :: Quickstarts :: Maven :: Zero-Config (Jitpack) |
| description | How to use Eclipse JKube from Jitpack |

Add the following to the pom.xml

```xml
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
<pluginRepositories>
  <pluginRepository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </pluginRepository>
</pluginRepositories>
```

Replace the plugin references:

From:
```xml
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>kubernetes-maven-plugin</artifactId>
  <version>${jkube.version}</version>
</plugin>
<! -- ... -->
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>openshift-maven-plugin</artifactId>
  <version>${jkube.version}</version>
</plugin>
```
To:
```xml
<plugin>
  <groupId>com.github.eclipse.jkube</groupId>
  <artifactId>kubernetes-maven-plugin</artifactId>
  <version>master-SNAPSHOT</version>
</plugin>
<! -- ... -->
<plugin>
  <groupId>com.github.eclipse.jkube</groupId>
  <artifactId>openshift-maven-plugin</artifactId>
  <version>master-SNAPSHOT</version>
</plugin>
```

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by rbrishabh**
fixes #732
Hey @manusa! How does this look?
Let me know if this needs any changes!
Thanks

### CODE REVIEW

**Comment by manusa** [comment]
As stated in the [Gitter channel](https://gitter.im/eclipse/jkube?at=60d301cab60c3137c389a181), you need to create a **new** Quickstart following the zero-config one.

You **don't** have to replace any of the existing files, those are OK.

**Comment by manusa** [comment]
Also, you should go over the PR template checklist (you deleted it for this PR) and check the boxes that apply, especially the ones that state that you tested your work on OpenShift and Kubernetes.

**Comment by rbrishabh** [comment]
Ok! I got it

**Comment by rbrishabh** [comment]
Will start a new PR. Closing this

**Pull request closed without merging**
