### PR TITLE
Add check for vertx gradle plugin with isApplicable method in VertxHealthCheckEnricher

### LINKED ISSUE #1633: VertxHealthCheckEnricher should also check Vertx Gradle Plugin in `isApplicable()`
### Component

JKube Kit

### Description
VertxHealthCheckEnricher has this `isApplicable` method which is used for checking whether we should apply this enricher on a project or not. 

https://github.com/eclipse/jkube/blob/61345823be63c73cf334649e33e9c5146f9d5f7a/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java#L104-L107

We should also add logic to check Vertx Gradle Plugin here as well, just like we have it in [VertxGenerator](https://github.com/eclipse/jkube/blob/master/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/VertxGenerator.java#L52)

### Acceptance Criteria
- [x] VertxHealthCheckEnricher should also consider Vertx Gradle Plugin in `isApplicable`
- [x] VertxHealthCheckEnricher documentation is ported to Gradle

### PR DESCRIPTION
**Pull request by Devamparikh**
## Description
chore(method modification): Add check for vertx gradle plugin with isApplicable method in VertxHealthCheckEnricher (#1633)

Fix #1633 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
VertxHealthCheckEnrichers's configuration seems to have really different nested enricher configuration. It works for properties but it doesn't seem to be working when configuration is provided from Gradle Groovy DSL configuration. We need to look into this

**Comment by manusa** [comment]
> VertxHealthCheckEnrichers's configuration seems to have really different nested enricher configuration. It works for properties but it doesn't seem to be working when configuration is provided from Gradle Groovy DSL configuration. We need to look into this

Should this PR be merged then?

**Comment by rohanKanojia** [comment]
I think we should fix https://github.com/eclipse/jkube/issues/1649 first then merge this one

**Comment by rohanKanojia** [comment]
Should be ready once https://github.com/eclipse/jkube/pull/1673 gets merged

**Comment by manusa** [comment]
Now that #1673 is merged, we need to rebase this one.

**Review by manusa — APPROVED** [review]

**Pull request merged**
