### PR TITLE
More readable, efficient code for buildServiceTest

### PR DESCRIPTION
**Pull request by Devamparikh**
## Description
Simplified verify() call to remove argument matchers and to be more readable.
This PR is the fix for #1413

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.org/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have implemented unit tests to cover my changes
 - [x] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

Let me know if there is any thing more I can do to help ;)

### CODE REVIEW

**Review by manusa — APPROVED** [review]

**Review by sunix — APPROVED** [review]
Minor: could you use https://www.conventionalcommits.org/ style for the commit message ?
Thanks !

**Review by rohanKanojia — APPROVED** [review]

**Comment by Devamparikh** [comment]
Do you suggest to change commit to  `fix: #1413 Simplified Mockito verify call and made it easy to read` ? or do I lack anything? Please let me know. Thanks.

**Comment by rohanKanojia** [comment]
I think it should be `fix: Simplified Mockito verify the call and made it easy to read (#1413)`

**Comment by Devamparikh** [comment]
Okay thanks @rohanKanojia I'll update it now.

**Comment by sunix** [comment]
@Devamparikh I think it should be `chore(test): Simplified Mockito verify the call and made it easy to read (#1413)`
but you don't need to recreate the PR to rename a commit message.

**Comment by Devamparikh** [comment]
@sunix I have committed twice by mistake, Will this be okay? or should I create new PR?

**Pull request closed without merging**
